### ISSUE TITLE
[embedded wasmer llvm] subtraction overflow panic in State::peekn_extra

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#1005]
# Describe the bug

This bug happen when you are calling `wasmer::compile_with` from another rust binary compiled in debug.

``` sh
$ ./target/debug/compile_debug panic_substract_overflow.wasm
Start compile_debug
File path: "panic_substract_overflow.wasm"
thread 'main' panicked at 'attempt to subtract with overflow', XXX/wasmer/lib/llvm-backend/src/state.rs:244:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Issue come from line 244 of lib/llvm-backend/src/state.rs:
https://github.com/wasmerio/wasmer/blob/7bb570a7f93eab4e5e0894c713d859ef4129a019/lib/llvm-backend/src/state.rs#L239-L249

This issue is not happening with `wasmer` binary since an error will be through:
``` sh
$ wasmer run --backend llvm panic_substract_overflow.wasm
Error: Can't compile module: InternalError { msg: "Codegen(\"CodegenError { message: \\\"BinaryReaderError { message: \\\\\\\"invalid value stack\\\\\\\", offset: 18446744073709551615 }\\\" }\")" }
```

# Status of my environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.2 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
version: 7bb570a7f93eab4e5e0894c713d859ef4129a019

### Steps to reproduce

Download [panic_substract_overflow.zip](https://github.com/wasmerio/wasmer/files/3880317/panic_substract_overflow.zip)

Testing source code:
``` rust
use std::env;
use std::fs::{File};
use std::io;
use std::io::Read;
use std::path::PathBuf;


extern crate wasmer_llvm_backend;
extern crate wasmer_runtime_core;
extern crate wasmer_runtime;

use wasmer_runtime::{
    compile_with,
};
use wasmer_runtime_core::backend::Compiler;

/// Read the contents of a file
fn read_contents(path: &PathBuf) -> Result<Vec<u8>, io::Error> {
    let mut buffer: Vec<u8> = Vec::new();
    let mut file = File::open(path)?;
    file.read_to_end(&mut buffer)?;
    // We force to close the file
    drop(file);
    Ok(buffer)
}

fn get_llvm_compiler() -> impl Compiler {
    use wasmer_llvm_backend::LLVMCompiler;
    LLVMCompiler::new()
}

fn main() {
    println!("Start compile_debug");
  let args: Vec<String> = env::args().collect();

  // first argument is wasm file path
  let wasm_path = std::path::PathBuf::from(&args[1]);
    println!("File path: {:?}", wasm_path);

  let wasm_binary: Vec<u8> = read_contents(&wasm_path).unwrap();
    //println!("wasm_binary: {:?}", wasm_binary);

    // CALL THE API HERE
    let res = compile_with(&wasm_binary[..], &get_llvm_compiler());
    // CALL THE API HERE
    res.map_err(|x| println!("{:?}", x));
    println!("OK");
}
```

Run with:
``` sh
$ RUSTFLAGS=-g cargo build
$ ./target/debug/compile_debug panic_substract_overflow.wasm
File path: "panic_substract_overflow.wasm"
thread 'main' panicked at 'attempt to subtract with overflow', XXX/wasmer/lib/llvm-backend/src/state.rs:244:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

Ideally, substration overflow should be checked before calling `get` like in the `popn` function:
https://github.com/wasmerio/wasmer/blob/7bb570a7f93eab4e5e0894c713d859ef4129a019/lib/llvm-backend/src/state.rs#L260-L271

### Actual behavior

``` sh
$ RUST_BACKTRACE=1 ./target/debug/compile_debug panic_substract_overflow.wasm
Start compile_debug
File path: "../../../../consulting/wasmer/wasm-fuzz/crashes/panic_substract_overflow.wasm"
thread 'main' panicked at 'attempt to subtract with overflow', XXX/wasmer/lib/llvm-backend/src/state.rs:244:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: wasmer_llvm_backend::state::State::peekn_extra
             at XXX/wasmer/lib/llvm-backend/src/state.rs:244
  12: <wasmer_llvm_backend::code::LLVMFunctionCodeGenerator as wasmer_runtime_core::codegen::FunctionCodeGenerator<wasmer_llvm_backend::code::CodegenError>>::feed_event
             at XXX/wasmer/lib/llvm-backend/src/code.rs:1178
  13: wasmer_runtime_core::codegen::MiddlewareChain::run
             at XXX/wasmer/lib/runtime-core/src/codegen.rs:308
  14: wasmer_runtime_core::parse::read_module
             at XXX/wasmer/lib/runtime-core/src/parse.rs:277
  15: <wasmer_runtime_core::codegen::StreamingCompiler<MCG,FCG,RM,E,CGEN> as wasmer_runtime_core::backend::Compiler>::compile
             at XXX/wasmer/lib/runtime-core/src/codegen.rs:225
  16: wasmer_runtime_core::compile_with
             at XXX/wasmer/lib/runtime-core/src/lib.rs:115
  17: compile_debug::main
             at src/main.rs:44
  18: std::rt::lang_start::{{closure}}
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/rt.rs:64
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  22: std::panicking::try
             at src/libstd/panicking.rs:275
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  25: std::rt::lang_start
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/rt.rs:64
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
Fixed
