### ISSUE TITLE
[singlepass backend] panic when unwraping read_table result (BrTable opcode)

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#1051]
### Describe the bug

`wasmer` using the `singlepass` backend will panic when:
- Result of `read_table` is unwraped even if this result is an Error.

``` sh
$ ./target/release/wasmer run --backend singlepass panic_unwrap_brtable_singlepass.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BinaryReaderError { message: "Invalid var_u32", offset: 4 }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

https://github.com/wasmerio/wasmer/blob/d639748a20d201391e899e0b27af0ec1755d3885/lib/singlepass-backend/src/codegen_x64.rs#L6451-L6452

### Status of my environment

```sh
$ echo "`./target/release/wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.11.0 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
version: 71b342e5b1348b310d96266dfdff7a7bcd76c159

### Steps to reproduce

Download [panic_unwrap_brtable_singlepass.zip](https://github.com/wasmerio/wasmer/files/3940153/panic_unwrap_brtable_singlepass.zip)

``` sh
$ unzip panic_unwrap_brtable_singlepass.zip
$ ./target/release/wasmer run --backend singlepass panic_unwrap_brtable_singlepass.wasm
```

### Expected behavior

`wasmer` should return and propagate the Error using `?`.

### Actual behavior

``` sh
$ ./target/release/wasmer run --backend singlepass panic_unwrap_brtable_singlepass.wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BinaryReaderError { message: "Invalid var_u32", offset: 4 }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Additional context

Once fixing patch #1052 applied, 
``` sh
$ ./target/release/wasmer run --backend singlepass panic_unwrap_brtable_singlepass.wasm 
Error: Can't compile module: InternalError { msg: "Codegen(\"CodegenError { message: \\\"BrTable read_table: BinaryReaderError { message: \\\\\\\"Invalid var_u32\\\\\\\", offset: 4 }\\\" }\")" }
```

**Comment by syrusakbary** [comment]
This issue should now be fixed on master. Closing :)
