### ISSUE TITLE
WAPM panic while executing install command

### ISSUE THREAD

**Issue by skyao** [wasmerio/wasmer#1340]
### Describe the bug

 I installed wasmer, and then try to use wapm. 

Following the document,

https://docs.wasmer.io/ecosystem/wapm/getting-started

### Steps to reproduce

1. install wasmer in linux 
2. execute install command

    ```sh
    $ wapm install cowsay
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:     Error(Url(RelativeUrlWithoutBase))', src/libcore/result.rs:1188:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
    ```

### Additional context

1. OS

    Linux mint 19.3,  (based on ubuntu 18.04.1), with linux kernel 5.3

    ```sh
    $ uname --all
    Linux skywork 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    ```

2. wasmer version 0.16.2

    ```sh
   $ wasmer --version
   wasmer 0.16.2
    ```

**Comment by skyao** [comment]
More detail information, by command "RUST_BACKTRACE=1 wapm install cowsay":

```bash
$ RUST_BACKTRACE=1 wapm install cowsay
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Url(RelativeUrlWithoutBase))', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: sentry::transport::ReqwestHttpTransport::new_internal
  15: <sentry::transport::DefaultTransportFactory as sentry::transport::TransportFactory>::create_transport
  16: sentry::client::Client::with_options
  17: sentry::client::init
  18: wapm::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  23: std::panicking::try
             at src/libstd/panicking.rs:270
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by syrusakbary** [comment]
Hi @skyao, we are taking a look on this now.
Thanks for reporting it!

**Comment by syrusakbary** [comment]
@skyao we tried in Linux, macOS and Windows and we were unable to reproduce the issue.

Is it possible that you have a firewall that might be blocking the request somehow?

**Comment by MarkMcCaskey** [comment]
Good call -- we should prevent sentry failures from blocking it looks like!

**Comment by skyao** [comment]
I tried this example again in this linux, it's OK now. 

Don't know what happens ....... 

Sorry for this.

**Comment by MarkMcCaskey** [comment]
@skyao no problem, I've filed an issue on wapm to solve the underlying problem!  Even if we can't reproduce it, I think I know what the underlying cause is and we can fix that!
