### ISSUE TITLE
Regression in master: panic triggered by passing negative values to host functions

### ISSUE THREAD

**Issue by mejedi** [wasmerio/wasmer#1596]
Passing `-1` as rights to `__wasi_path_open` triggers panic in the current master, works just fine in the latest release. 

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.17.1 | rustc 1.46.0 (04488afe3 2020-08-24) | x86_64
```

```
$ (cd ~/wasmer.git && git describe --tags)
0.17.1-2043-gd7893fe5b
```

### Steps to reproduce

 1. `test.c`:

```c
#include <wasi/core.h>
#include <wasi/libc-find-relpath.h>
#include <string.h>
#include <stdio.h>

int main() {
  const char *p = "/tmp";
  int fd = __wasilibc_find_relpath(p, 0, 0, &p);
  __wasi_fd_t res;
  __wasi_errno_t rc;
  rc = __wasi_path_open(fd, 0, p, strlen(p),
                        __WASI_O_DIRECTORY, -1, -1, 0, &res);
  if (rc == 0) printf("fd %d\n", res);
  else printf("error %d\n", rc);
  return 0;
}
```

  2. `wasicc test.c -o test.wasm`

  3. run using Wasmer binary from master: `~/wasmer.git/target/release/wasmer run --dir=/ test.wasm`

### Expected behavior

A file descriptor is opened and `fd N` line is printed. This is what I'm getting with the latest release:

```
$ wasmer run --dir=/ test.wasm
fd 5
```

### Actual behavior

Wasmer binary from master panics:

```
thread 'main' panicked at 'out of range type conversion attempt (tried to convert `i64` to `u64`): TryFromIntError(())', /home/nickz/wasmer.git/lib/api/src/externals/function.rs:600:43
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: <Func as wasmer::externals::function::inner::HostFunction<(A1,A2,A3,A4,A5,A6,A7,A8,A9),Rets,wasmer::externals::function::inner::WithEnv,Env>>::function_body_ptr::func_wrapper
  16: <unknown>
  17: <unknown>
  18: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by syrusakbary** [comment]
Good catch! Thanks for the bug report @mejedi
