### ISSUE TITLE
Crash when calling a zero arg function

### ISSUE THREAD

**Issue by liamappelbe** [wasmerio/wasmer#1626]
### Describe the bug
I've been using version 0.17.1 of the wasmer C API fine for a while, but I just tried calling a zero arg function using wasmer_export_func_call, and it crashed with this stack trace (using RUST_BACKTRACE=1):

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-c-api-0.17.1/src/export.rs:510:17
stack backtrace:
   0: rust_begin_unwind
             at /b/s/w/ir/k/rust/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /b/s/w/ir/k/rust/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /b/s/w/ir/k/rust/library/core/src/panicking.rs:62
   3: wasmer_export_func_call
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I was calling this exact function on an earlier version of wasmer without any issues, so it seems to be a regression (though my set up was a bit different, so there a chance it's not actually a regression).

### Steps to reproduce
I compiled this C code to wasm using [WasmFiddle](https://wasdk.github.io/WasmFiddle/):

```c
int x = 999;
void set(int a, int b) { x = a + b; }
int get() { return x; }
```

Then I instantiated the resulting wasm code using Wasmer, and called `get()`, then `set(123, 456)`, then `get()`.

### Expected behavior
The first `get()` should return 999, and the second should return 579. This is what I see when I call those functions in WasmFiddle.

### Actual behavior
The first `get()` crashes with the above stack trace. It seems like it's trying to iterate over the args, but there aren't any.

### Additional context
Wasmer C API version: 0.17.1
Rustc version: rustc 1.47.0-nightly (cbe7c5ce7 2020-08-11)
uname -m: x86_64

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report!  I wasn't able to reproduce it with

```C
void print_wasmer_error()
{
    int error_len = wasmer_last_error_length();
    printf("Error len: `%d`\n", error_len);
    char *error_str = malloc(error_len);
    wasmer_last_error_message(error_str, error_len);
    printf("Error str: `%s`\n", error_str);
}

int main()
{
    wasmer_import_t imports[] = {};

    // Read the wasm file bytes
    FILE *file = fopen("assets/zero-arg-functions.wasm", "r");
    fseek(file, 0, SEEK_END);
    long len = ftell(file);
    uint8_t *bytes = malloc(len);
    fseek(file, 0, SEEK_SET);
    fread(bytes, 1, len, file);
    fclose(file);

    printf("Instantiating\n");
    wasmer_instance_t *instance = NULL;
    wasmer_result_t compile_result = wasmer_instantiate(&instance, bytes, len, imports, 0);
    printf("Compile result:  %d\n", compile_result);
    if (compile_result != WASMER_OK) {
            print_wasmer_error();
    }

    assert(compile_result == WASMER_OK);

    wasmer_exports_t *exports = NULL;
    wasmer_instance_exports(instance, &exports);

    const wasmer_export_t* set_export = wasmer_exports_get(exports, 1);
    const wasmer_export_t* get_export = wasmer_exports_get(exports, 2);
    const wasmer_export_func_t* get_func = wasmer_export_to_func(get_export);
    const wasmer_export_func_t* set_func = wasmer_export_to_func(set_export);

    wasmer_value_t get_params[] = {};
    wasmer_value_t get_results[] = { { .tag = WASM_I32, .value = 0 } };
    wasmer_result_t call_result = wasmer_export_func_call(get_func, get_params, 0, get_results, 1);
    printf("Call result:  %d\n", call_result);
    if (call_result != WASMER_OK) {
            print_wasmer_error();
    }
    assert(call_result == WASMER_OK);

    wasmer_value_t set_params[] = { { .tag = WASM_I32, .value = 41 },
                                    { .tag = WASM_I32, .value = 1  } };
    wasmer_value_t set_results[] = {};
    call_result = wasmer_export_func_call(set_func, set_params, 2, set_results, 0);
    printf("Call result:  %d\n", call_result);
    if (call_result != WASMER_OK) {
            print_wasmer_error();
    }
    assert(call_result == WASMER_OK);

    call_result = wasmer_export_func_call(get_func, get_params, 0, get_results, 1);
    printf("Call result:  %d\n", call_result);
    if (call_result != WASMER_OK) {
            print_wasmer_error();
    }
    assert(call_result == WASMER_OK);

    printf("Destroy instance\n");
    wasmer_instance_destroy(instance);
    return 0;
}
```

on master so it should be fixed with the latest version of Wasmer.

Currently we generally don't support older versions of Wasmer but if there are blocking issues preventing you from using the latest release we'll prioritize those!  And if the specific issues can't be resolved in a timely manner then perhaps we can ship a patch release for the older version.

**Comment by liamappelbe** [comment]
I'm happy to update if it fixes the bug, but it looks like the new version hasn't propagated to wasmer-runtime-c-api in crates.io yet. I'm not in a rush to fix this though, so I'll just wait for the update and see if it fixes it.
