### ISSUE TITLE
alpine build error

### ISSUE THREAD

**Issue by phpstatic** [wasmerio/wasmer#1766]
### Describe the bug

try build from alpine, get this error:

```sh

  --- stderr
  autoreconf: Entering directory `.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal -I m4
  autoreconf: configure.ac: tracing
  autoreconf: running: libtoolize --copy
  autoreconf: running: /usr/bin/autoconf
  autoreconf: running: /usr/bin/autoheader
  autoreconf: running: automake --add-missing --copy --no-force
  configure.ac:31: installing './compile'
  configure.ac:19: installing './install-sh'
  configure.ac:19: installing './missing'
  Makefile.am: installing './depcomp'
  doc/Makefile.am:3: installing 'doc/mdate-sh'
  doc/Makefile.am:3: installing 'doc/texinfo.tex'
  autoreconf: Leaving directory `.'
  ../src/java_raw_api.c: In function 'ffi_java_raw_call':
  ../src/java_raw_api.c:317:3: warning: 'ffi_java_raw_to_ptrarray' is deprecated [-Wdeprecated-declarations]
    317 |   ffi_java_raw_to_ptrarray (cif, raw, avalue);
        |   ^~~~~~~~~~~~~~~~~~~~~~~~
  ../src/java_raw_api.c:76:1: note: declared here
     76 | ffi_java_raw_to_ptrarray (ffi_cif *cif, ffi_java_raw *raw, void **args)
        | ^~~~~~~~~~~~~~~~~~~~~~~~
  ../src/java_raw_api.c: In function 'ffi_java_translate_args':
  ../src/java_raw_api.c:328:3: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
    328 |   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
        |   ^~~~~~~~~~~~
  ../src/java_raw_api.c:45:1: note: declared here
     45 | ffi_java_raw_size (ffi_cif *cif)
        | ^~~~~~~~~~~~~~~~~
  ../src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
    331 |   ffi_java_ptrarray_to_raw (cif, avalue, raw);
        |   ^~~~~~~~~~~~~~~~~~~~~~~~
  ../src/java_raw_api.c:157:1: note: declared here
    157 | ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw)
        | ^~~~~~~~~~~~~~~~~~~~~~~~
  ../src/java_raw_api.c: In function 'ffi_prep_java_raw_closure':
  ../src/java_raw_api.c:369:3: warning: 'ffi_prep_java_raw_closure_loc' is deprecated [-Wdeprecated-declarations]
    369 |   return ffi_prep_java_raw_closure_loc (cl, cif, fun, user_data, cl);
        |   ^~~~~~
  ../src/java_raw_api.c:337:1: note: declared here
    337 | ffi_prep_java_raw_closure_loc (ffi_java_raw_closure* cl,
        | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ar: `u' modifier ignored since `D' is the default (see `U')
  ar: `u' modifier ignored since `D' is the default (see `U')
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib/libclang.so.10 could not be opened: Dynamic loading not supported"', /opt/build/php/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.52.0/src/lib.rs:1895:31
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:483:5
     1: core::panicking::panic_fmt
               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/panicking.rs:85:14
     2: core::option::expect_none_failed
               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/option.rs:1268:5
     3: core::result::Result<T,E>::expect
     4: core::ops::function::FnOnce::call_once
     5: lazy_static::lazy::Lazy<T>::get::{{closure}}
     6: std::sync::once::Once::call_once::{{closure}}
     7: std::sync::once::Once::call_inner
               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sync/once.rs:419:21
     8: std::sync::once::Once::call_once
     9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
    10: bindgen::ensure_libclang_is_loaded
    11: bindgen::Bindings::generate
    12: bindgen::Builder::generate
    13: build_script_build::generate_bindings
    14: build_script_build::main
    15: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
warning: 2 warnings emitted

error: build failed
```

### Steps to reproduce

build from alpine/edge,  already install musl-dev clang-dev llvm-dev. 

```sh
ls -alFh /usr/lib/libclang.so.10
-rwxr-xr-x    1 root     root       26.0M Jul 30 14:48 /usr/lib/libclang.so.10*
 ldd /usr/lib/libclang.so.10
	/lib/ld-musl-x86_64.so.1 (0x7fcca8fcf000)
	libLLVM-10.so => /usr/lib/../lib/libLLVM-10.so (0x7fcca38de000)
	libstdc++.so.6 => /usr/lib/../lib/libstdc++.so.6 (0x7fcca373d000)
	libgcc_s.so.1 => /usr/lib/../lib/libgcc_s.so.1 (0x7fcca3723000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fcca8fcf000)
	libffi.so.7 => /usr/lib/../lib/libffi.so.7 (0x7fcca3718000)
	libz.so.1 => /lib/libz.so.1 (0x7fcca36fe000)
	libxml2.so.2 => /usr/lib/../lib/libxml2.so.2 (0x7fcca35d4000)
	liblzma.so.5 => /usr/lib/../lib/liblzma.so.5 (0x7fcca35b1000)
```

### Expected behavior

expect build c-api static lib.

**Comment by MarkMcCaskey** [comment]
Hmm, I'm not sure what's wrong with libclang here but this is caused by our libffi dependency.  You can install libffi yourself (looks like it's already installed) and pass the `system-libffi` feature when building the c-api and it'll probably fix it.

See the `build-capi-cranelift-system-libffi` makefile command for an example of this.

This seems most likely to be an issue with libffi itself. Though ```the `libclang` shared library at /usr/lib/libclang.so.10 could not be opened: Dynamic loading not supported``` suggests that perhaps the libclang you have or the system you're running on doesn't support dynamic loading?

**Comment by syrusakbary** [comment]
@phpstatic could it be possible to have the build script so we can try to reproduce the issue?

That way it will be much easier to find a fix, thanks!

**Comment by phpstatic** [comment]
I am try build a minimal size static library to link with php,  so I pick features singlepass,wasi.

I try upgrade to 1.0.0-alpha4, find out 1.0.0-alpha4 can not work with php extension because api change. so I build old version, then I can not get it build. (I also upgrade rustup toolchain)

This is how I build wasmer.
```sh
rustup default nightly || exit $?
rustup update nightly || exit $?
rustup target add x86_64-unknown-linux-musl --toolchain=nightly
git reset --hard 1.0.0-alpha3
cargo clean
cargo build --manifest-path lib/c-api/Cargo.toml --release --target x86_64-unknown-linux-musl --no-default-features --features singlepass,wasi,system-libff --verbose 
error: Package `wasmer-c-api v1.0.0-alpha3 (/opt/build/php/build/wasmer/lib/c-api)` does not have these features: `system-libff`
```

without system-libff  get libclang.so.10 error.  I  also try build with other version, get same error.

remove ` --target x86_64-unknown-linux-musl` fix the problem.
