### ISSUE TITLE
singlepass crashes compiling fdiv + fcopysign

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#2159]
Testcase:

```
(module
  (func (export "_start") (result f64)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.div
    f64.copysign
  )
)
```

fails to build with singlepass:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lib/compiler-singlepass/src/codegen_x64.rs:513:60
```

the relevant part of the backtrace is:

```
   4: wasmer_compiler_singlepass::codegen_x64::FuncGen::emit_relaxed_binop
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:513:28
   5: wasmer_compiler_singlepass::codegen_x64::FuncGen::canonicalize_nan
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:341:9
   6: wasmer_compiler_singlepass::codegen_x64::FuncGen::feed_operator
             at /home/nicholas/wasmer/lib/compiler-singlepass/src/codegen_x64.rs:3570:33
```

**Comment by nlewycky** [comment]
Another testcase, this time with floor + copysign, also showing that it occurs with `f32` as well as `f64`:
```
(module
  (func (export "_start") (result f32)
    f32.const 0x0p+0 (;=0;)
    f32.const 0x0p+0 (;=0;)
    f32.floor
    f32.copysign
  )
)
```
