### ISSUE TITLE
Where to get `nginx.wasm`? Or potential error?

### ISSUE THREAD

**Issue by rauchg** [wasmerio/wasmer#22]
I was able to get it from:
https://www.wasmjit.org/blog/hello-world.html

Which points to
https://www.dropbox.com/sh/lmz3nnz92jx9szh/AAA-YOEHxwM_nki8jX0uFRuqa?dl=0

That when run results in:
```
▲  wasmer run nginx.wasm
thread 'main' panicked at 'illegal instruction', src/sighandler.rs:28:23
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
▲  wasmer run nginx.wasm
thread 'main' panicked at 'illegal instruction', src/sighandler.rs:28:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: wasmer::sighandler::install_sighandler
   7: wasmer::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: main
```

Running `wasmer` on:

```
▲  uname -a
Darwin Guillermos-MacBook-Air.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:40:55 PDT 2018; root:xnu-4903.221.2~1/RELEASE_X86_64 x86_64
```

**Comment by lachlansneff** [comment]
We're still working on getting `nginx.wasm` to run. There are quite a few apis that we need to implement first. I'm guessing the `illegal instruction` error you're getting is the wasm trapping somewhere because the mocked apis aren't returning right.

**Comment by rauchg** [comment]
@lachlansneff makes sense! I went by the homepage. Thank you

**Comment by appcypher** [comment]
Related PR #27

**Comment by syrusakbary** [comment]
While we merged #27, there is still some work in progress that we need to do in order to have nginx fully running.
We are super close though :)

**Comment by syrusakbary** [comment]
Wasmer can now run nginx successfully!

# Steps to have it running
1. Install wasmer (via `curl https://get.wasmer.io -sSfL | sh` or `wasmer self-update` if you are in wasmer >= 0.1.1)
2. Create a nginx config file in `/usr/local/nginx/conf/nginx.conf` with the contents:

```
events {
  worker_connections  1024;
}

# We need this for now, as we want to run nginx as a worker
daemon off;
master_process off;

http {
 server {
    listen       8080;
    # Accept any connection
    server_name _;

    location / {
        # You can replace this directory to any other you want to serve
        root /Users/syrus/Downloads/nginx-1.15.3/html;
        index index.html;
    }
  }
}
```

3. Execute nginx `wasmer runnginx.wasm` (you can get it from here: https://github.com/wasmerio/wasmer/blob/master/examples/nginx.wasm)


And now you should be able to access: http://localhost:8080/

## Notes

We are working on containerization, so step 2 will be much easier in the future.
