### ISSUE TITLE
Panic in the singlepass compiler

### ISSUE THREAD

**Issue by matklad** [wasmerio/wasmer#2347]
```rust
fn main() {
    let jit = wasmer::JIT::new(wasmer::Singlepass::new());
    let store = wasmer::Store::new(&jit.engine());
    let bytes = vec![
        0, 97, 115, 109, 1, 0, 0, 0, 1, 6, 1, 96, 1, 124, 1, 127, 2, 1, 0, 3, 3, 2, 0, 0, 10, 20,
        2, 3, 0, 0, 11, 14, 0, 65, 255, 135, 140, 120, 183, 155, 155, 32, 0, 166, 0, 11,
    ];
    let _ = wasmer::Module::new(&store, bytes);
}
```

This results in 

```
thread 'tests::error_cases::test_simple_contract' panicked at 'called `Option::unwrap()` on a `None` value', /home/matklad/.cargo/git/checkouts/wasmer-0210ff4327f3d2ae/a98937b/lib/compiler-singlepass/src/codegen_x64.rs:513:60
```

wasmer "1.0.2"

**Comment by olonho** [comment]
Minimalized contract looks like that:
```
 (module
  (type (;0;) (func (param f64) (result i32)))
  (func (;1;) (type 0) (param f64) (result i32)
    f64.const 0
    f64.ceil
    local.get 0
    f64.copysign
    unreachable))
```
removing `f64.ceil` or  `f64.copysign` makes bug to go away. Crash happens here:
```
           at /Users/nike/.rustup/toolchains/1.51.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: wasmer_compiler_singlepass::codegen_x64::FuncGen::emit_relaxed_binop
             at /Users/nike/.cargo/git/checkouts/wasmer-0210ff4327f3d2ae/a98937b/lib/compiler-singlepass/src/codegen_x64.rs:513:28
   5: wasmer_compiler_singlepass::codegen_x64::FuncGen::canonicalize_nan
             at /Users/nike/.cargo/git/checkouts/wasmer-0210ff4327f3d2ae/a98937b/lib/compiler-singlepass/src/codegen_x64.rs:341:9
   6: wasmer_compiler_singlepass::codegen_x64::FuncGen::feed_operator
             at /Users/nike/.cargo/git/checkouts/wasmer-0210ff4327f3d2ae/a98937b/lib/compiler-singlepass/src/codegen_x64.rs:3570:33
```
Seems ad-hoc register allocator in Singlepass runs out of registers.

**Comment by Hywan** [comment]
Thank you for the bug report!

**Comment by syrusakbary** [comment]
Tested and reproduced the bug. It seems was introduced in Wasmer 1.0

**Comment by chenyukang** [comment]
I'm fixing this.
