### ISSUE TITLE
Document rust wasm32-unknown-emscripten build tool versions working with wasmer

### ISSUE THREAD

**Issue by jcaesar** [wasmerio/wasmer#2498]
### Summary

Finding a working combination of versions for rustc and emscripten is black magic, many fail with arcane error messages on missing C++ symbols. And the only working combination I found so far (emcc 1.39.20, rustc 1.47.0) runs me into #1898.

It would be really nice to document how to set up and environment that builds emscripten rust executables that can be run with wasmer.

### Additional details

(non-working) env setup example:
```Dockerfile
FROM docker.io/library/debian:bullseye as bin
RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -yq \
        build-essential \
        cmake \
        curl \
        file \
        git \
        python3 \
        python \
        sudo \
        && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    useradd rust --user-group --create-home --shell /bin/bash
USER rust
RUN cd /home/rust && git clone https://github.com/emscripten-core/emsdk.git && cd /home/rust/emsdk && ./emsdk install 1.39.20 && ./emsdk activate 1.39.20
ENV PATH=/home/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.47 --profile default --no-modify-path && \
    rustup target add wasm32-unknown-emscripten
RUN cd ~ \
	&& git clone https://github.com/wasmerio/rust-cli-app-example ex \
	&& git config --global advice.detachedHead false \
	&& git -C ex checkout ee2f893d7d702f3e5efeee30633f7ef4f6723be5
WORKDIR /home/rust/ex
RUN bash -c ". /home/rust/emsdk/emsdk_env.sh && cargo -v build --release --locked --target=wasm32-unknown-emscripten"

FROM docker.io/library/busybox
RUN wget https://github.com/wasmerio/wasmer/releases/download/2.0.0/wasmer-linux-musl-amd64.tar.gz \
	&& echo e978d0e9298481bfd79b48a6446b63b8fcc6aa7560e22a37fb3a08705a88375b \ wasmer-linux-musl-amd64.tar.gz | sha256sum -c \
	&& tar xvf wasmer-linux-musl-amd64.tar.gz \
	&& rm wasmer-linux-musl-amd64.tar.gz
COPY --from=bin /home/rust/ex/target/wasm32-unknown-emscripten/release/rust_cli_app_example.wasm .
RUN wasmer run rust_cli_app_example.wasm -- -g
```

**Comment by Hywan** [comment]
Hello,

I'm not sure it's the role of Wasmer to write documentation for emscripten. Maybe it must be part of the emscripten's official documentation. Or maybe just a code snippet in the `README.md` of the `wasmer-emscripten` crate.

**Comment by jcaesar** [comment]
Hi Hywan!

"Document how to build a wasm32-emscripten binary from rust" is definitely not wasmer's job, no. (Maybe Rust's, but I'm not sure either.)

But wasmer doesn't support binaries built by all versions of emscripten (at least #1898 makes it seem like that), and documenting which versions of emscripten are supported by wasmer is wasmer's job, imho.

> Or maybe just a code snippet in the README.md of the wasmer-emscripten crate.
That'd be great.

**Comment by jcaesar** [comment]
All right, I found a combination that looks like it would work, but then trying to run the binary just hangs. I'll have a deeper look at that another day.

<details>
<summary>Fockerdile</summary>

```Dockerfile
FROM docker.io/library/debian:bullseye as bin
RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -yq \
        build-essential \
        cmake \
        curl \
        file \
        git \
        python3 \
        python \
        sudo \
        && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    useradd rust --user-group --create-home --shell /bin/bash
USER rust
RUN cd /home/rust && git clone https://github.com/emscripten-core/emsdk.git && cd /home/rust/emsdk && ./em
sdk install 1.38.43 && ./emsdk activate 1.38.43
ENV PATH=/home/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.34 --profile default --no-modify-pa
th && \
    rustup target add wasm32-unknown-emscripten
RUN cd ~ \
        && git clone https://github.com/wasmerio/rust-cli-app-example ex \
        && git config --global advice.detachedHead false \
        && git -C ex checkout ee2f893d7d702f3e5efeee30633f7ef4f6723be5
WORKDIR /home/rust/ex
RUN mkdir -p .cargo \
        && echo >>.cargo/config \
        && echo >>.cargo/config [target.wasm32-unknown-emscripten] \
        && echo >>.cargo/config 'rustflags = [ "-C", "link-args=-s EMITTING_JS=1" ]' \
        && echo >>.cargo/config
# EMITTING_JS is the old version of STANDALONE_WASM.
# It's necessary because emscripten would minify import/export names on release builds.
# Alternatively, change -O3 to -O2
#RUN true \
#       && echo >>Cargo.toml \
#       && echo >>Cargo.toml [profile.release] \
#       && echo >>Cargo.toml opt-level = '2' \
#       && echo >>Cargo.toml
#RUN cat .cargo/config && false
RUN bash -c ". /home/rust/emsdk/emsdk_env.sh && cargo -v build --locked --target=wasm32-unknown-emscripten
"

FROM docker.io/library/busybox
RUN wget https://github.com/wasmerio/wasmer/releases/download/2.0.0/wasmer-linux-musl-amd64.tar.gz \
        && echo e978d0e9298481bfd79b48a6446b63b8fcc6aa7560e22a37fb3a08705a88375b \ wasmer-linux-musl-amd64
.tar.gz | sha256sum -c \
        && tar xvf wasmer-linux-musl-amd64.tar.gz \
        && rm wasmer-linux-musl-amd64.tar.gz
COPY --from=bin /home/rust/ex/target/wasm32-unknown-emscripten/debug/rust_cli_app_example.wasm .
#ENTRYPOINT ["/bin/sh", "inspect", "rust_cli_app_example.wasm"]
ENTRYPOINT ["/bin/wasmer", "run", "rust_cli_app_example.wasm", "--disable-cache", "--"]
```

</details>

**Comment by syrusakbary** [comment]
Awesome, closing the issue.

**Comment by jcaesar** [comment]
All right, I dug a bit deeper. 
My Dockerfile gets me the following executable: [rust_cli_app_example.wasm.gz](https://github.com/wasmerio/wasmer/files/7941827/rust_cli_app_example.wasm.gz)

If I run this in wasmer

```
#0  0x00007ffff7f5d600 in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007ffff7f56503 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x000055555602263e in std::sys::unix::mutex::Mutex::lock (self=0x5555587647b0) at /rustc/1.58.0/library/std/src/sys/unix/mutex.rs:63
#3  0x0000555555fbc97d in std::sys_common::mutex::MovableMutex::raw_lock (self=0x555558975830) at /rustc/1.58.0/library/std/src/sys_common/mutex.rs:76
#4  0x0000555555e61fe5 in std::sync::mutex::Mutex<wasmer_emscripten::EmscriptenData>::lock<wasmer_emscripten::EmscriptenData> (self=0x555558975830) at /rustc/1.58.0/library/std/src/sync/mutex.rs:267
#5  0x0000555555e81238 in wasmer_emscripten::env::get_emscripten_data (ctx=0x555558866be0) at lib/emscripten/src/env/mod.rs:57
#6  0x0000555555ffe0d6 in wasmer_emscripten::emscripten_target::invoke_i (ctx=0x555558866be0, index=3215) at lib/emscripten/src/emscripten_target.rs:175
#7  0x0000555555e42920 in core::ops::function::Fn::call<fn(&wasmer_emscripten::EmEnv, i32) -> i32, (&wasmer_emscripten::EmEnv, i32)> () at /rustc/1.58.0/library/core/src/ops/function.rs:70
#8  0x0000555555ec70fd in wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper::{closure#0}<i32, i32, i32, wasmer_emscripten::EmEnv, fn(&wasmer_emscripten::EmEnv, i32) -> i32> () at /home/julius/code/wasmer/lib/api/src/sys/externals/function.rs:1357
#9  0x0000555556016b19 in core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<i32, core::convert::Infallible>, wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper::{closure#0}> (self=..., _args=()) at /rustc/1.58.0/library/core/src/panic/unwind_safe.rs:271
#10 0x0000555555fe488f in std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper::{closure#0}>, core::result::Result<i32, core::convert::Infallible>> (data=0x7fffffff83f0) at /rustc/1.58.0/library/std/src/panicking.rs:406
#11 0x0000555555ffa0fb in __rust_try ()
#12 0x0000555555fd2344 in std::panicking::try<core::result::Result<i32, core::convert::Infallible>, core::panic::unwind_safe::AssertUnwindSafe<wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper::{closure#0}>> (f=...) at /rustc/1.58.0/library/std/src/panicking.rs:370
#13 0x0000555555f96fb1 in std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper::{closure#0}>, core::result::Result<i32, core::convert::Infallible>> (f=...) at /rustc/1.58.0/library/std/src/panic.rs:133
#14 0x0000555555ec0f52 in wasmer::sys::externals::function::inner::{impl#31}::function_body_ptr::func_wrapper<i32, i32, i32, wasmer_emscripten::EmEnv, fn(&wasmer_emscripten::EmEnv, i32) -> i32> (env=0x555558866be0, A1=3215) at /home/julius/code/wasmer/lib/api/src/sys/externals/function.rs:1356
#15 0x00007ffff5c366e1 in ?? ()
#16 0x0000000000000000 in ?? ()
```

It looks like wasmer is running in a deadlock somewhere in its emscripten code. :(

@syrusakbary Would you mind reopening this? The issue is very much still there, after all. (I should probably open a separate issue for the deadlock.)
