### ISSUE TITLE
bash almost works however in certain stack rewinds it will crash

### ISSUE THREAD

**Issue by john-sharratt** [wasmerio/wasmer#3225]
hey guys - for now I have to park this as it costs me too much time and I think there are easier ways to find the cause... however once we get onto the WASIX stuff a bit more perhaps someone can help me debug this.
dash already works quite well.
bash which will give a much better interactive experience (color, history, etc...) mostly works except it crashes when unwinding and rewinding the stack in certain scenarios....

```
     Running `/prog/wasmer/target/debug/wasmer --enable-threads --allow-multiple-wasi-versions --use sharrattj/coreutils --map-command catsay=/prog/ate/wasmer-web/public/bin/catsay.wasm /prog/ate/wasmer-web/public/bin/bash.wasm`
bash.wasm-5.1# echo blah | catsay
 ______
< blah >
 ------
  \                              _
   \                            | \
    \                           | |
     \                          | |
      \    |\                   | |
       \  /, ~\                / /
         X     `-.....-------./ /
          ~-. ~  ~              |
             \             /    |
              \  /_     ___\   /
              | /\ ~~~~~   \ |
              | | \        || |
              | |\ \       || )
             (_/ (_/      ((_/
bash.wasm-5.1# ls
bin
dev
etc
tmp
usr
error: failed to run `/prog/ate/wasmer-web/public/bin/bash.wasm`
│   1: RuntimeError: out of bounds memory access
           at <unnamed> (<module>[2034]:0x185530)
           at <unnamed> (<module>[1187]:0xf41d7)
           at <unnamed> (<module>[944]:0xb3fe0)
           at <unnamed> (<module>[914]:0xad41a)
           at <unnamed> (<module>[913]:0xa924d)
           at <unnamed> (<module>[265]:0x2a673)
           at <unnamed> (<module>[263]:0x2a0e3)
           at <unnamed> (<module>[262]:0x29bce)
           at <unnamed> (<module>[49]:0x47ef)
           at <unnamed> (<module>[1814]:0x15d466)
           at <unnamed> (<module>[2080]:0x188379)
╰─▶ 2: heap_get_oob
john@AlienWorld:/prog/wasmer/lib/cli$
```

By doing some comments tricky I've managed to isolate it down to asyncify (or at least somewhere near there) - where in certain call stacks if I attempt to rewind on those call chains it will fail. I tried a heap of things but time has run out.
Anyway I need to get back to porting the new WASIX code back to Deploy - will keep you all posted

**Comment by syrusakbary** [comment]
It's curious, I think this issue might be somewhat related to what SWC reported when upgrading to Wasmer 3.0 (it was a weird/random OOB error).

https://github.com/swc-project/swc/issues/5480#issuecomment-1217462425

Does this error happen on both the browser and the server or just in the server @john-sharratt ?

**Comment by john-sharratt** [comment]
I've got `bash` working in the browser now (without `coreutils`) and the problem also occurs there so can confirm it happens in both server and browser.

```
RACE /prog/wasmer/lib/wasi/src/syscalls/mod.rs:3843 wasi[0]::rewinding (memory_stack_size=640, rewind_size=132)
780.main.js:631 TRACE /prog/wasmer/lib/wasi/src/syscalls/mod.rs:3926 wasi[0]::stack_checkpoint - restored - (ret=0)
780.main.js:631 TRACE /prog/wasmer/lib/wasi/src/syscalls/mod.rs:423 wasi[0]::clock_time_get clock_id: 0, precision: 1000000000
780.main.js:631 TRACE /prog/wasmer/lib/wasi/src/syscalls/mod.rs:442 time: 1666044262808000000 => 0
780.main.js:631 DEBUG /prog/wasmer/lib/wasi/src/bin_factory/exec.rs:145 exec-failed: runtime error - RuntimeError: JsValue(RuntimeError: memory access out of boundsRuntimeError: memory access out of bounds    at wasm://wasm/007507e2:wasm-function[2034]:0x185530    at wasm://wasm/007507e2:wasm-function[1187]:0xf41d7    at wasm://wasm/007507e2:wasm-function[944]:0xb3fe0    at wasm://wasm/007507e2:wasm-function[914]:0xad41a    at wasm://wasm/007507e2:wasm-function[913]:0xa924d    at wasm://wasm/007507e2:wasm-function[265]:0x2a673    at wasm://wasm/007507e2:wasm-function[263]:0x2a0e3    at wasm://wasm/007507e2:wasm-function[262]:0x29bce    at wasm://wasm/007507e2:wasm-function[49]:0x47ef    at wasm://wasm/007507e2:wasm-function[1814]:0x15d466    at wasm://wasm/007507e2:wasm-function[2080]:0x188379    at http://localhost:9000/780.main.js:1190:29    at handleError (http://localhost:9000/780.main.js:398:18)    at imports.wbg.__wbg_apply_bd59f70527113b67 (http://localhost:9000/780.main.js:1189:68)    at _ZN6js_sys7Reflect5apply17h0d71e325448aea06E (http://localhost:9000/fe71a54e12f82d7f3068.wasm:wasm-function[5956]:0x4534c3)    at _ZN6wasmer2js9externals8function8Function4call17h3fabdcd4f7b271ddE (http://localhost:9000/fe71a54e12f82d7f3068.wasm:wasm-function[744]:0x27d15a)    at _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hc623fc8d49d808a5E (http://localhost:9000/fe71a54e12f82d7f3068.wasm:wasm-function[208]:0x997b8)    at _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17hd76e01d76e4b0a4aE (http://localhost:9000/fe71a54e12f82d7f3068.wasm:wasm-function[3385]:0x3e7cee)    at wasm_entry_point (http://localhost:9000/fe71a54e12f82d7f3068.wasm:wasm-function[277]:0x125b66)    at wasm_entry_point (http://localhost:9000/780.main.js:369:10)    at self.onmessage (http://localhost:9000/942.main.js:111:17))
780.main.js:631 DEBUG /prog/wasmer/lib/wasi/src/bin_factory/exec.rs:155 main() has exited on bash with 9999
```

**Comment by syrusakbary** [comment]
Since this issue is happening also in the browser, I think it's reasonable to think that the issue is not in the Wasm runtime, but perhaps in either our syscall implementations or somewhere in bash code
