### ISSUE TITLE
Tests fail to compile

### ISSUE THREAD

**Issue by svenstaro** [wasmerio/wasmer#364]
### Describe the bug

Running `make test` fails with 

```
make test
# We use one thread so the emscripten stdouts doesn't collide
cargo test --all --exclude wasmer-runtime-c-api --exclude wasmer-emscripten --exclude wasmer-spectests --exclude wasmer-singlepass-backend -- 
   Compiling wasmer-llvm-backend v0.3.0 (/home/svenstaro/src/wasmer/lib/llvm-backend)
   Compiling zbox v0.6.1 (https://github.com/wasmerio/zbox?branch=bundle-libsodium#113c62bf)
error: failed to run custom build command for `wasmer-llvm-backend v0.3.0 (/home/svenstaro/src/wasmer/lib/llvm-backend)`
process didn't exit successfully: `/home/svenstaro/src/wasmer/target/debug/build/wasmer-llvm-backend-b67bdfc87c65aa23/build-script-build` (exit code: 101)
--- stdout
NUM_JOBS = Some("8")
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = Some("-I/usr/include -std=c++11  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS ")
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I/usr/include" "-std=c++11" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-o" "/home/svenstaro/src/wasmer/target/debug/build/wasmer-llvm-backend-274ffe10762e2655/out/cpp/object_loader.o" "-c" "cpp/object_loader.cpp"
cargo:warning=cpp/object_loader.cpp:152:28: error: ‘LookupFlagsResult’ was not declared in this scope
cargo:warning=     virtual llvm::Expected<LookupFlagsResult> lookupFlags(const LookupSet& symbols) override {
cargo:warning=                            ^~~~~~~~~~~~~~~~~
cargo:warning=cpp/object_loader.cpp:152:28: note: suggested alternative: ‘LookupResult’
cargo:warning=     virtual llvm::Expected<LookupFlagsResult> lookupFlags(const LookupSet& symbols) override {
cargo:warning=                            ^~~~~~~~~~~~~~~~~
cargo:warning=                            LookupResult
cargo:warning=cpp/object_loader.cpp:152:45: error: template argument 1 is invalid
cargo:warning=     virtual llvm::Expected<LookupFlagsResult> lookupFlags(const LookupSet& symbols) override {
cargo:warning=                                             ^
cargo:warning=cpp/object_loader.cpp:142:42: error: ‘virtual llvm::Expected<std::map<llvm::StringRef, llvm::JITEvaluatedSymbol> > SymbolLookup::lookup(const LookupSet&)’ marked ‘override’, but does not override
cargo:warning=     virtual llvm::Expected<LookupResult> lookup(const LookupSet& symbols) override {
cargo:warning=                                          ^~~~~~
cargo:warning=cpp/object_loader.cpp:152:47: error: ‘virtual int SymbolLookup::lookupFlags(const LookupSet&)’ marked ‘override’, but does not override
cargo:warning=     virtual llvm::Expected<LookupFlagsResult> lookupFlags(const LookupSet& symbols) override {
cargo:warning=                                               ^~~~~~~~~~~
cargo:warning=cpp/object_loader.cpp: In member function ‘virtual int SymbolLookup::lookupFlags(const LookupSet&)’:
cargo:warning=cpp/object_loader.cpp:153:9: error: ‘LookupFlagsResult’ was not declared in this scope
cargo:warning=         LookupFlagsResult result;
cargo:warning=         ^~~~~~~~~~~~~~~~~
cargo:warning=cpp/object_loader.cpp:153:9: note: suggested alternative: ‘LookupResult’
cargo:warning=         LookupFlagsResult result;
cargo:warning=         ^~~~~~~~~~~~~~~~~
cargo:warning=         LookupResult
cargo:warning=cpp/object_loader.cpp:156:13: error: ‘result’ was not declared in this scope
cargo:warning=             result.emplace(symbol, symbol_lookup(symbol).getFlags());
cargo:warning=             ^~~~~~
cargo:warning=cpp/object_loader.cpp:156:13: note: suggested alternative: ‘result_t’
cargo:warning=             result.emplace(symbol, symbol_lookup(symbol).getFlags());
cargo:warning=             ^~~~~~
cargo:warning=             result_t
cargo:warning=cpp/object_loader.cpp:159:16: error: ‘result’ was not declared in this scope
cargo:warning=         return result;
cargo:warning=                ^~~~~~
cargo:warning=cpp/object_loader.cpp:159:16: note: suggested alternative: ‘result_t’
cargo:warning=         return result;
cargo:warning=                ^~~~~~
cargo:warning=                result_t
cargo:warning=cpp/object_loader.cpp: In constructor ‘WasmModule::WasmModule(const uint8_t*, size_t, callbacks_t)’:
cargo:warning=cpp/object_loader.cpp:182:18: error: cannot declare variable ‘symbol_resolver’ to be of abstract type ‘SymbolLookup’
cargo:warning=     SymbolLookup symbol_resolver(callbacks);
cargo:warning=                  ^~~~~~~~~~~~~~~
cargo:warning=cpp/object_loader.cpp:138:8: note:   because the following virtual functions are pure within ‘SymbolLookup’:
cargo:warning= struct SymbolLookup : llvm::JITSymbolResolver {
cargo:warning=        ^~~~~~~~~~~~
cargo:warning=In file included from /usr/include/llvm/ExecutionEngine/RuntimeDyld.h:20,
cargo:warning=                 from cpp/object_loader.hh:3,
cargo:warning=                 from cpp/object_loader.cpp:1:
cargo:warning=/usr/include/llvm/ExecutionEngine/JITSymbol.h:357:16: note: 	‘virtual void llvm::JITSymbolResolver::lookup(const LookupSet&, llvm::JITSymbolResolver::OnResolvedFunction)’
cargo:warning=   virtual void lookup(const LookupSet &Symbols,
cargo:warning=                ^~~~~~
cargo:warning=/usr/include/llvm/ExecutionEngine/JITSymbol.h:364:3: note: 	‘virtual llvm::Expected<std::set<llvm::StringRef> > llvm::JITSymbolResolver::getResponsibilitySet(const LookupSet&)’
cargo:warning=   getResponsibilitySet(const LookupSet &Symbols) = 0;
cargo:warning=   ^~~~~~~~~~~~~~~~~~~~
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I/usr/include" "-std=c++11" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-o" "/home/svenstaro/src/wasmer/target/debug/build/wasmer-llvm-backend-274ffe10762e2655/out/cpp/object_loader.o" "-c" "cpp/object_loader.cpp" with args "c++" did not execute successfully (status code exit code: 1).

', /home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.34/src/lib.rs:2368:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
```

### Steps to reproduce

1. Clone the repo
2. cd to repo
3. make test

### Expected behavior

Tests should compile and run.

### Actual behavior

Tests fail to compile.

### Additional context

This is on Arch Linux. I tested gcc 8.2, gcc 8.3, clang 8.0.0 and they all fail.

**Comment by lachlansneff** [comment]
Currently, we support linking against llvm 7.0. It seems like you're linking against llvm 8.0. Soon, we will automatically download and link against the correct llvm version, but it's not in master yet.

**Comment by svenstaro** [comment]
Is that documented in any location that I missed?

**Comment by syrusakbary** [comment]
That's not documented yet, our fault.
We are working on improving docs so it's easier to replicate the setup locally.

Also, once we merge #353 it should be much easier to do :)

**Comment by svenstaro** [comment]
Well, I'll leave this bug open at any rate. You decide what to do with it.
Seems like a tracking bug for clang 8 at this point.

**Comment by huangjj27** [comment]
But I get similar error on My windows(msvc) installation, using wasmer@297215f6bc4604eb1c004ac5b9ef9f5b3eba4fd8:
```ps
PS E:\learning-rust\rust-wasi-tutorial\target\wasm32-unknown-wasi\release> wasmer run main.wasm input.txt out.txt
error opening input: failed to find a preopened file descriptor through which "input.txt" could be opened
```

**Comment by MarkMcCaskey** [comment]
> But I get similar error on My windows(msvc) installation, using wasmer@297215f6bc4604eb1c004ac5b9ef9f5b3eba4fd8:
> 
> ```postscript
> PS E:\learning-rust\rust-wasi-tutorial\target\wasm32-unknown-wasi\release> wasmer run main.wasm input.txt out.txt
> error opening input: failed to find a preopened file descriptor through which "input.txt" could be opened
> ```

Hello @huangjj27 ; try the latest master and use the `--dir` flag to specify the current directory as a preopened directory.  Let me know if that doesn't fix it!

**Comment by huangjj27** [comment]
All right, it compiled at 0.4.0, but Error me with this:

```
PS E:\learning-rust\rust-wasi-tutorial\target\wasm32-unknown-wasi\release> wasmer run main.wasm --dir . input.txt out.txt
thread 'main' panicked at 'Could not find file: Os { code: 5, kind: PermissionDenied, message: "拒绝访问。" }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

when I run wasmer as administrator, it keep warning me with windows sandbox. Why?

**Comment by MarkMcCaskey** [comment]
Hi!

That command will be passing no arguments to the wasm program and trying to
open three directories (`.`, `input.txt`, `out.txt`) which is probably not
what you want.

Try `wasmer run main.wasm --dir=. -- input.txt out.txt`!

The reason is that `--dir` without an `=` reads everything after it as a
preopened directory (until `--`) and also that `wasmer` needs `--` to
separate wasmer arguments from program arguments.

I'll look in to increasing visibility of what wasmer is doing and improving
the error messages here -- thanks for the report!

**Comment by huangjj27** [comment]
I tried:
```
wasmer run main.wasm --dir=. -- input.txt out.txt
thread 'main' panicked at 'Could not find file: Os { code: 5, kind: PermissionDenied, message: "拒绝访问。" }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I think it's about the permission difference between windows and *nix

**Comment by xmclark** [comment]
@huangjj27 The administrator dialog error you are seeing is expected whenever running a program as administrator on windows. 

It seems that we have identified a bug with our wasi implementation. The issue stems from how we are pre-opening directories. The rust file system abstraction let us do something we shouldn't be allowed to do on windows: open a directory like a file. 

We are going to find a solution for this..

**Comment by MarkMcCaskey** [comment]
@huangjj27 this should be fixed by #397 !  Thanks for letting us know!

**Comment by huangjj27** [comment]
@MarkMcCaskey Yes, it is fixed, Successfually running it.  Thanks!

**Comment by huangjj27** [comment]
I think we can add test stage to CI so that we can found any test problem as soon as possible?

**Comment by huangjj27** [comment]
`make test` on WS(Ubuntu 18.04, with initial llvm6 removed and llvm-7 installed by apt) fail:
```
error: failed to run custom build command for `wasmer-llvm-backend v0.4.0 (/home/huangjj27/wasmer/lib/llvm-backend)`
process didn't exit successfully: `/home/huangjj27/wasmer/target/debug/build/wasmer-llvm-backend-3d1adc9289268860/build-script-build` (exit code: 101)
--- stdout
Didn't find usable system-wide LLVM.
No suitable version of LLVM was found system-wide or pointed
                  to by LLVM_SYS_70_PREFIX.

                  Consider using `llvmenv` to compile an appropriate copy of LLVM, and
                  refer to the llvm-sys documentation for more information.

                  llvm-sys: https://crates.io/crates/llvm-sys
                  llvmenv: https://crates.io/crates/llvmenv

--- stderr
thread 'main' panicked at 'Could not find a compatible version of LLVM', lib/llvm-backend/build.rs:83:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

what value should be set to `LLVM_SYS_70_PREFIX`?

**Comment by syrusakbary** [comment]
This issue should now be fixed on `master`. Closing the issue
