### ISSUE TITLE
Flaky threading snapshot test

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3845]
### Describe the bug

The Linux CLI integration tests just spuriously failed in #3831 ([logs](https://github.com/wasmerio/wasmer/actions/runs/4873091824/jobs/8704687610#step:26:461)). Looking at the snapshot test's diff, it seems like some multi-threaded operations happened out of order, causing different output to be printed.

```
---- test_snapshot_tokio stdout ----
[tests/integration/cli/tests/snapshot.rs:314] &cmd = "/home/runner/work/wasmer/wasmer/tests/integration/cli/../../../target/release/wasmer" "--enable-threads" "--allow-multiple-wasi-versions" "/tmp/.tmpM0G58O"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/integration/cli/tests/snapshots/snapshot__snapshot_tokio.snap
Snapshot: snapshot_tokio
Source: tests/integration/cli/tests/snapshot.rs:564
error: test failed, to rerun pass `-p wasmer-integration-tests-cli --test snapshot`
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    9     9 │   },
   10    10 │   "result": {
   11    11 │     "Success": {
   12    12 │       "stdout": "",
   13       │-      "stderr": "step-1\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-2\nstep-3\ndata match verified (len=128)\nstep-4\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-5\nstep-A1\nstep-B1\nstep-B2\nstep-A2\ndata match verified (len=128)\nstep-A3\nstep-B3\nstep-B4\nstep-A4\ndata match verified (len=128)\nstep-A5\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-A6\nstep-A7\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-A8\nall done\n",
         13 │+      "stderr": "step-1\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-2\nstep-3\ndata match verified (len=128)\nstep-4\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-5\nstep-A1\nstep-B1\nstep-B2\nstep-A2\ndata match verified (len=128)\nstep-A3\nstep-A4\nstep-B3\nstep-B4\ndata match verified (len=128)\nstep-A5\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-A6\nstep-A7\nreceived ErrorKind::WouldBlock - receiving on an empty channel\nstep-A8\nall done\n",
   14    14 │       "exit_code": 0
   15    15 │     }
   16    16 │   }
   17    17 │ }
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'main' panicked at 'snapshot assertion for 'snapshot_tokio' failed in line 564', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: insta::runtime::finalize_assertion
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
   3: insta::runtime::assert_snapshot
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:686:9
   4: snapshot::test_snapshot_tokio
             at ./tests/snapshot.rs:564:5
   5: snapshot::test_snapshot_tokio::{{closure}}
             at ./tests/snapshot.rs:560:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_snapshot_tokio

test result: FAILED. 40 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 88.24s
```

**Comment by theduke** [comment]
Would also be fixed by #3768 .
