### ISSUE TITLE
Flaky web server snapshot test

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#3892]
### Describe the bug

CI in #3852 seems to have spuriously failed ([GitHub Actions](https://github.com/wasmerio/wasmer/actions/runs/5045424783/jobs/9050454800)). I thought I'd record the failure so we know to come back to it when we fix up flaky WASIX tests.

```
---- test_snapshot_web_server stdout ----
[tests/integration/cli/tests/snapshot.rs:331] &cmd = "/home/runner/work/wasmer/wasmer/tests/integration/cli/../../../target/release/wasmer" "--enable-threads" "--net" "--allow-multiple-wasi-versions" "--use" "sharrattj/coreutils" "--use" "sharrattj/wasmer-sh" "--include-webc" "/tmp/.tmpdBbrj3" "--include-webc" "/tmp/.tmpO4X94H" "--include-webc" "/tmp/.tmpw21gCb" "/tmp/.tmp07Pkhi"
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
error: test failed, to rerun pass `-p wasmer-integration-tests-cli --test snapshot`
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
http request: http://localhost:7777/main.js.size
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests/integration/cli/tests/snapshots/snapshot__snapshot_web_server.snap
Snapshot: snapshot_web_server
Source: tests/integration/cli/tests/snapshot.rs:716
────────────────────────────────────────────────────────────────────────────────
Expression: snapshot
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
   21    21 │     "enable_threads": true,
   22    22 │     "enable_network": true
   23    23 │   },
   24    24 │   "result": {
   25       │-    "Success": {
   26       │-      "stdout": "",
   27       │-      "stderr": "# # # # ",
   28       │-      "exit_code": 0
   29       │-    }
         25 │+    "Error": "Command failed: timeout while performing HTTP request\n\nSTDOUT:\n\n\nSTDERR:\n# # # # \u001b[2m2023-05-22T13:02:22.0[479](https://github.com/wasmerio/wasmer/actions/runs/5045424783/jobs/9050454800#step:26:480)25Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mstatic_web_server::logger\u001b[0m\u001b[2m:\u001b[0m logging level: info\n\u001b[2m2023-05-22T13:02:22.052456Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mstatic_web_server::server\u001b[0m\u001b[2m:\u001b[0m config file: \"./cfg/config.toml\"\n\u001b[2m2023-05-22T13:02:22.052765Z\u001b[0m \u001b[31mERROR\u001b[0m \u001b[2mstatic_web_server::server\u001b[0m\u001b[2m:\u001b[0m server failed to start up: failed to bind to [::]:80 address\n\nCaused by:\n    Operation not permitted (os error 63)\n# \n"
   30    26 │   }
   31    27 │ }
────────────┴───────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'main' panicked at 'snapshot assertion for 'snapshot_web_server' failed in line 716', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37[553](https://github.com/wasmerio/wasmer/actions/runs/5045424783/jobs/9050454800#step:26:554)bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: insta::runtime::finalize_assertion
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:569:9
   3: insta::runtime::assert_snapshot
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.29.0/src/runtime.rs:686:9
   4: snapshot::test_snapshot_web_server
             at ./tests/snapshot.rs:716:5
   5: snapshot::test_snapshot_web_server::{{closure}}
             at ./tests/snapshot.rs:689:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
make: *** [Makefile:630: test-integration-cli-ci] Error 101
    test_snapshot_web_server

test result: FAILED. 51 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 210.17s
```

### Additional context

CC #3847, #3845

**Comment by ptitSeb** [comment]
maybe it's an actual bug.
