### ISSUE TITLE
Unable to use `wasmer run ...` inside a running WASIX program

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer#4269]
### Describe the bug

When using the `wasmer` CLI natively (e.g. on MacOS), the `wasmer run` virtual command that WASIX programs get access to will always trigger a panic.

```sh
$ wasmer -vV
wasmer 4.2.2 (b75bcc4 2023-10-04)
binary: wasmer-cli
commit-hash: b75bcc4d7510298d6e8699e126f9fb4c453b1db5
commit-date: 2023-10-04
host: aarch64-apple-darwin
compiler: singlepass,cranelift

$ rustc -vV
rustc 1.73.0-nightly (f3623871c 2023-08-06)
binary: rustc
commit-hash: f3623871cfa0763c95ebd6ceafaa6dc2e44ca68f
commit-date: 2023-08-06
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Steps to reproduce

```console
$ RUST_BACKTRACE=1 wasmer run sharrattj/bash
bash-5.1# wasmer run python/python
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.27/src/client/connect/dns.rs:121:24
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tokio::runtime::scheduler::Handle::current
   3: tokio::runtime::blocking::pool::spawn_blocking
   4: <reqwest::dns::gai::GaiResolver as reqwest::dns::resolve::Resolve>::resolve
   5: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
   6: <hyper_rustls::connector::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
   7: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
   8: reqwest::connect::with_timeout::{{closure}}
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
  12: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  13: hyper::client::client::Client<C,B>::retryably_send_request::{{closure}}
  14: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  15: <wasmer_wasix::http::reqwest::ReqwestHttpClient as wasmer_wasix::http::client::HttpClient>::request::{{closure}}
  16: <wasmer_wasix::runtime::resolver::wapm_source::WapmSource as wasmer_wasix::runtime::resolver::source::Source>::query::{{closure}}
  17: <D as wasmer_wasix::runtime::resolver::source::Source>::query::{{closure}}
  18: <wasmer_wasix::runtime::resolver::multi_source::MultiSource as wasmer_wasix::runtime::resolver::source::Source>::query::{{closure}}
  19: wasmer_wasix::runtime::resolver::source::Source::latest::{{closure}}
  20: wasmer_wasix::bin_factory::binary_package::BinaryPackage::from_registry::{{closure}}
  21: wasmer_wasix::os::command::builtins::cmd_wasmer::CmdWasmer::run::{{closure}}
  22: futures_executor::local_pool::block_on
  23: <wasmer_wasix::os::command::builtins::cmd_wasmer::CmdWasmer as wasmer_wasix::os::command::VirtualCommand>::exec
  24: wasmer_wasix::os::command::Commands::exec
  25: wasmer_wasix::bin_factory::exec::<impl wasmer_wasix::bin_factory::BinFactory>::try_built_in
  26: wasmer_wasix::syscalls::wasix::proc_exec::proc_exec::{{closure}}
  27: wasmer_wasix::syscalls::wasix::proc_exec::proc_exec
  28: std::panicking::try
  29: corosensei::coroutine::on_stack::wrapper
  30: _stack_call_trampoline
  31: wasmer_vm::trap::traphandlers::on_host_stack
  32: wasmer::sys::externals::function::<impl wasmer::externals::function::HostFunction<T,(A1,A2,A3,A4),Rets,wasmer::externals::function::WithEnv> for Func>::function_callback::func_wrapper
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Rayon: detected unexpected panic; aborting
bash-5.1#[1]    92285 abort      RUST_BACKTRACE=1 wasmer run sharrattj/bash
```

### Expected behavior

The Python interepreter should start and show a prompt.

### Actual behavior

We get a panic because a syscall calls an asynchronous function and uses `__asyncify_light()` to wait until it completes. However, because that async function calls into tokio code and `__asyncify_light()` is just a wrapper around `futures::executor::block_on()`, we end up calling tokio code outside of a tokio runtime and trigger a panic.

### Additional Context

You can see the original conversation and discovery [on Slack](https://wasmerio.slack.com/archives/C04193Z3RHS/p1697615457417929).

**Comment by gluax** [comment]
Hey all, I'm still getting this error but instead when trying to use wasmer_wasix in rust:

```
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs/home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs::777777::2121:       
:
there is no reactor running, must be called from the context of a Tokio 1.x runtimethere is no reactor running, must be called from the context of a Tokio 1.x runtime

stack backtrace:
thread '<unnamed>' panicked at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs:777:21:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
thread '<unnamed>' panicked at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs:777:21:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:150:5
   3: tokio::runtime::scheduler::Handle::current
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/mod.rs:106:27
   4: tokio::runtime::handle::Handle::current
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:139:20
   5: <virtual_fs::host_fs::Stdin as core::default::Default>::default
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs:777:21
   6: <alloc::boxed::Box<T> as core::default::Default>::default
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:1247:18
   7: wasmer_wasix::state::builder::WasiEnvBuilder::build_init::{{closure}}
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:647:54
   8: core::option::Option<T>::unwrap_or_else
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:979:21
   9: wasmer_wasix::state::builder::WasiEnvBuilder::build_init
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:644:67
  10: wasmer_wasix::state::builder::WasiEnvBuilder::finalize
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:769:20
  11: seda_runtime::runtime::internal_run_vm
             at ./runtime/core/src/runtime.rs:22:24
  12: seda_runtime::runtime::start_runtime
             at ./runtime/core/src/runtime.rs:105:18
  13: <seda_node::runtime_job::RuntimeWorker as actix::handler::Handler<seda_node::runtime_job::RuntimeJob>>::handle
             at ./node/src/runtime_job.rs:52:25
  14: <actix::sync::SyncContextEnvelope<M> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:369:13
  15: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/address/envelope.rs:55:9
  16: actix::sync::SyncContext<A>::run
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:279:21
  17: actix::sync::SyncArbiter<A>::start_with_thread_builder::{{closure}}
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:144:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:150:5
   3: tokio::runtime::scheduler::Handle::current
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/mod.rs:106:27
   4: tokio::runtime::handle::Handle::current
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:139:20
   5: <virtual_fs::host_fs::Stdin as core::default::Default>::default
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/virtual-fs-0.9.0/src/host_fs.rs:777:21
   6: <alloc::boxed::Box<T> as core::default::Default>::default
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:1247:18
   7: wasmer_wasix::state::builder::WasiEnvBuilder::build_init::{{closure}}
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:647:54
   8: core::option::Option<T>::unwrap_or_else
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:979:21
   9: wasmer_wasix::state::builder::WasiEnvBuilder::build_init
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:644:67
  10: wasmer_wasix::state::builder::WasiEnvBuilder::finalize
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-wasix-0.16.0/src/state/builder.rs:769:20
  11: seda_runtime::runtime::internal_run_vm
             at ./runtime/core/src/runtime.rs:22:24
  12: seda_runtime::runtime::start_runtime
             at ./runtime/core/src/runtime.rs:105:18
  13: <seda_node::runtime_job::RuntimeWorker as actix::handler::Handler<seda_node::runtime_job::RuntimeJob>>::handle
             at ./node/src/runtime_job.rs:52:25
  14: <actix::sync::SyncContextEnvelope<M> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:369:13
  15: <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy<A>>::handle
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/address/envelope.rs:55:9
  16: actix::sync::SyncContext<A>::run
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:279:21
  17: actix::sync::SyncArbiter<A>::start_with_thread_builder::{{closure}}
             at /home/gluax/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-0.13.1/src/sync.rs:144:21
```

I'm assuming it's because a new version of `wasix` was not released, as it seems similar to the issue here. Or please correct me if that logic is wrong :)

**Comment by gluax** [comment]
Confirmed: it is the fact that `wasix` hasn't had an update with this fix yet.

**Comment by gluax** [comment]
Nope it seems something else is wrong, even if I do `wasmer` and `wasmer-wasix` I still get that panic...

seems to be pointing to:

```rust
/// A wrapper type around Stdin that implements `VirtualFile`.
#[derive(Debug)]
#[cfg_attr(feature = "enable-serde", derive(Serialize, Deserialize))]
pub struct Stdin {
    read_buffer: Arc<std::sync::Mutex<Option<Bytes>>>,
    handle: Handle,
    inner: tokio::io::Stdin,
}
impl Default for Stdin {
    fn default() -> Self {
        Self {
            handle: Handle::current(),
            read_buffer: Arc::new(std::sync::Mutex::new(None)),
            inner: tokio::io::stdin(),
        }
    }
}
```

So does this require being in a `tokio` runtime? Couldn't find any docs about `wasmer-wasix` requiring it.
