### ISSUE TITLE
Initiate panic at allocatting memory

### ISSUE THREAD

**Issue by XinyuShe** [wasmerio/wasmer#4283]
### Describe the bug

I am a beginner with Wasmer. I have just created a new Docker container specifically to install Wasmer and attempted to use 'wasmer run test.wasm.' However, even in this simple scenario, it still throws an 'initiate panic' error.
So I suppose this might be a bug.

```sh
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-79-generic x86_64)
:~$ docker -v
Docker version 24.0.5, build ced0996
wasmer run test.wasm
```
### Steps to reproduce
```sh
root@:/home# wasmer run filea5.wasm
⠋ Initializing the WebAssembly VM                                                                                       thread '<unnamed>' panicked at 'failed to set up alternative stack guard page: Cannot allocate memory (os error 12)', library/std/src/sys/unix/stack_overflow.rs:147:13
stack backtrace:
thread '<unnamed>' panicked at 'failed to set up alternative stack guard page: Cannot allocate memory (os error 12)', library/std/src/sys/unix/stack_overflow.rs:147:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
fatal runtime error: failed to initiate panic, error 5
Aborted
root@:/home# wasmer run filea5.wasm --singlepass
⠉ Initializing the WebAssembly VM                                                                                       thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', /home/runner/work/wasmer/wasmer/lib/wasix/src/runtime/task_manager/tokio.rs:69:22
⠙ Initializing the WebAssembly VM                                                                                       stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: wasmer_wasix::runtime::task_manager::tokio::TokioTaskManager::new
   4: wasmer_cli::commands::run::wasi::Wasi::prepare_runtime
   5: wasmer_cli::commands::run::Run::execute_inner
   6: wasmer_cli::commands::run::Run::execute
   7: wasmer_cli::cli::wasmer_main_inner
   8: wasmer_cli::cli::wasmer_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
⠂ Initializing the WebAssembly VM                                                                                       
root@:/home# rustc -V
rustc 1.73.0 (cc66ad468 2023-10-03)
```
My docker stats:
```
CPU %     MEM USAGE / LIMIT    MEM %     NET I/O          BLOCK I/O        PIDS
0.00%     6.578GiB / 1008GiB   0.65%     3.92GB / 102MB   187MB / 61.3GB   9673
```

**Comment by Michael-F-Bryan** [comment]
The Wasmer VM allocates 4GB of memory for an instance's linear memory and an extra 2GB for the guard page. Normally, your OS won't actually allocate this memory so it's not a problem (often called "overcommit" - the memory won't be allocated until it is touched). 

It's possible that Docker is blocking this for some reason. Can you try increasing your container's memory limit and trying again? There might also be an overcommit setting you can toggle.

**Comment by XinyuShe** [comment]
I retested with a Docker container with 8GB of memory, but I am still encountering the same issue.
