### ISSUE TITLE
Singlepass panics: ImpossibleRelocation

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#4519]
Singlepass panic with an ImpossibleRelocation error when compiling the following packages:

- `dermagen/siof`
    - 1.0.3        (issue on ARM)
        ```bash
        $ wasmer run dermagen/siof@1.0.3 --singlepass --entrypoint=siof
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called Result::unwrap() on an Err value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
        ```bash
        $ wasmer compile atom_0.wasm -o atom_0.wasmu --singlepass --target "x86_64-unknown-linux-musl" -m avx  
        Compiler: singlepass
        Target: x86_64-unknown-linux-musl
        ✔ File compiled successfully to `atom_0.wasmu`.
        ```
        
    - 1.0.2 (issue only on ARM)
        
        ```bash
        $ wasmer run dermagen/siof@1.0.2 --singlepass --entrypoint=siof
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```

        ```bash
        $ wasmer compile atom_0.wasm -o atom_0.wasmu --singlepass --target "x86_64-unknown-linux-musl" -m avx 
        Compiler: singlepass
        Target: x86_64-unknown-linux-musl
        ✔ File compiled successfully to `atom_0.wasmu`.
        ```
        
- pancake/r2  (issue only on ARM)
    - 5.6.2  (issue only on ARM)
        
        ```bash
        $ wasmer run pancake/r2@=5.6.2 --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        
        ```bash
        $ wasmer compile atom_0.wasm -o atom_0.wasmu --singlepass --target "x86_64-unknown-linux-musl" -m avx
        Compiler: singlepass
        Target: x86_64-unknown-linux-musl
        ✔ File compiled successfully to `atom_0.wasmu`.
        ```
        
    - 5.4.4 (issue only on ARM)
            
        ```bash
        $ wasmer run pancake/r2@=5.4.4 --singlepass -- -v
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```

        ```bash
        $ wasmer compile atom_0.wasm -o atom_0.wasmu --singlepass --target "x86_64-unknown-linux-musl" -m avx 
        Compiler: singlepass
        Target: x86_64-unknown-linux-musl
        ✔ File compiled successfully to `atom_0.wasmu`.
        ```
        
    - 5.4.3
        
        ```bash
        $ wasmer run pancake/r2@=5.4.3 --singlepass
        error: The WEBC file doesn't contain any executable commands
        ```
        
- pancake/rasm2
    - 5.6.2
        
        ```bash
        $ wasmer run pancake/rasm2@=5.6.2 --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
- kassandra/kassandra-node
    - 0.1.1
        
        ```bash
        $ wasmer run kassandra/kassandra-node@=0.1.1  --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
    - 0.1.0
        
        ```bash
        $ wasmer run kassandra/kassandra-node@=0.1.0  --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
- nturley/yosys
    - 0.1.0
        
        ```bash
        $ wasmer run nturley/yosys@=0.1.0 --singlepass
        error: The WEBC file doesn't contain any executable commands
        ```
        
    - 0.1.1
    - 0.1.2
        
        ```bash
        $ wasmer run nturley/yosys@=0.1.2 --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
- yehowshua/yosys
    - 0.9.2
        
        ```bash
        $ wasmer run yehowshua/yosys@=0.9.2 --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```
        
- php/php
    - 0.1.1
        
        ```bash
        $ wasmer run php/php@=0.1.1 --singlepass
        thread '<unnamed>' panicked at lib/compiler-singlepass/src/machine_arm64.rs:2294:35:
        called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ```

**Comment by syrusakbary** [comment]
#4559 is now merged. Closing

**Comment by ByteNacked** [comment]
Greetings,

Got the same error with the current main branch when using the singlepass compiler with the aarch64 target:

```bash
$ ./target/release/wasmer compile ./bug.wasm -o atom_0.wasmu --singlepass --target "aarch64-unknown-linux-musl"Compiler: singlepass

Target: aarch64-unknown-linux-musl
error: failed to compile `./bug.wasm`
╰─▶ 1: Compilation error: Assembler failed finalization with: ImpossibleRelocation(Dynamic(DynamicLabel(0)))

```

The program which reproduce this behavior consist of single function, with given below code fragment repeated 25000 times (originally used for benches). Program is here [bug.wat.zip](https://github.com/user-attachments/files/16366458/bug.wat.zip)

```
    i64.const 4705864922400277288
    i64.const 5816526446623108589
    i64.div_s
    drop
```

PS: I figured out the bug fix, gonna make PR soon.
