### ISSUE TITLE
I am not able to call a function, that has access to threading

### ISSUE THREAD

**Issue by Outfluencer** [wasmerio/wasmer#5316]
### Summary

I want to create a plugin system in rust using wasmer and wasix with full std support (thread::spawn and file system and so on)
I encountered the problem that threading was not supported without wasix

now i am using wasix and i compile my plugin with this command 
`cargo wasix build`

I try to call the CrustPlugin_QueryMetadata in my compiled plugin

```#[no_mangle]
pub extern "C" fn CrustPlugin_QueryMetadata() -> *const PluginMetadata {
    println!("CrustPlugin_QueryMetadata");
    thread::spawn( move || { // only for testing if all function would work
        fs::write("test.txt", "test").unwrap();
        panic!("test2");
    });
    &PLUGIN_METADATA as *const PluginMetadata
}
```

and i get this error
Error while importing "wasix_32v1"."getcwd": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })

This is the code i am currently using to load the wasm file

```
let mut store = Store::default();
let caps = Capabilities {
    insecure_allow_all: true,
    http_client: HttpClientCapabilityV1::new_allow_all(),
    threading: CapabilityThreadingV1::default()
};
let mut builder = WasiEnvBuilder::new("Crust");
builder.set_capabilities(caps);
let wasi_env = builder.build().unwrap();
let function_env = FunctionEnv::new(&mut store, wasi_env);
let imports = wasmer_wasix::generate_import_object_from_env(&mut store, &function_env, WasiVersion::Latest);
let module = Module::from_file(&store, path)?;
let instance = Instance::new(&mut store, &module, &imports)?;


let query_metadata: TypedFunction<(), WasmPtr<u8>> = instance.exports.get_typed_function(&store, "CrustPlugin_QueryMetadata")
    .map_err(|e| format!("Failed to get symbol 'CrustPlugin_QueryMetadata': {}", e))?;
```

if i change the WasiVersion to Wasix32v1 it also fails for another import

**Comment by Outfluencer** [comment]
the method load plugin i called inside a tokio runtime btw

**Comment by Arshia001** [comment]
Hey @Outfluencer!

Are you using the latest version of both wasmer and `wasmer_wasix` crates? This looks like it was caused by an outdated version of `wasmer_wasix`.

**Comment by Outfluencer** [comment]
wasmer = { version = "5.0.4" }
wasmer-wasix = "0.34.0"
both latest as long as i know

**Comment by Arshia001** [comment]
This is the syscall in question:

https://github.com/wasmerio/wasmer/blob/d585edf9076518136148e0d05545873b5debdf96/lib/wasix/src/lib.rs#L556

It's been there for a long time afaict, so something else must be going wrong... Can you share your code or a minimal repro please?

**Comment by Outfluencer** [comment]
Here a zip containing both repos the WasmerTest dir contains the programm that tries to read and execute the wasmer testplugin

I compiled the wasmer testplugin with: cargo wasix build

I want to get it running with full sdk support (just to remind of my goal)

Thank you for any investigations

[WasmerTestRepos.zip](https://github.com/user-attachments/files/18270336/WasmerTestRepos.zip)

**Comment by Arshia001** [comment]
@Outfluencer the error is happening because you're using `WasiVersion::Latest`, which translates to `WasiVersion::Snapshot1`. This is a [WASI](https://wasi.dev/) version. Your module is a [WASIX](https://wasix.org) module, so you need to pass in `WasiVersion::Wasix32v1`.

You can also use `wasmer_wasix::get_wasi_version` to automatically detect the appropriate version for your module.

**Comment by Outfluencer** [comment]
> if i change the WasiVersion to Wasix32v1 it also fails for another import

**Comment by Outfluencer** [comment]
Wasix32v1
thread 'main' panicked at src/main.rs:35:73:
called `Result::unwrap()` on an `Err` value: Link(Import("wasi_snapshot_preview1", "fd_write", UnknownImport(Function(FunctionType { params: [I32, I32, I32, I32], results: [I32] }))))
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\result.rs:1700
   3: enum2$<core::result::Result<wasmer::instance::Instance,enum2$<wasmer::errors::InstantiationError> > >::unwrap
             at C:\Users\Administrator\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1104
   4: WasmerTestX::main
             at .\src\main.rs:35
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at C:\Users\Administrator\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:250
   6: core::hint::black_box
             at C:\Users\Administrator\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\hint.rs:389
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\WasmerTestX.exe` (exit code: 101)

**Comment by Arshia001** [comment]
Oh, you're right, that only generates WASIX imports, so you'll still be missing WASI imports. Your module uses both, since WASIX is a superset of WASI. What you need is `import_object_for_all_wasi_versions`, but that's private. Also, this won't be the only thing you have to set up. All of this is done automatically if you go through `WasiEnvBuilder::instantiate`. Does that work for you?

**Comment by Arshia001** [comment]
To do this, you need:

```rust
    let mut builder = WasiEnvBuilder::new("Crust");
    builder.set_capabilities(caps);
    let module = Module::from_file(&store, wasm_path).unwrap();
    let (instance, wasi_env) = builder.instantiate(module, &mut store).unwrap();

    let query_metadata: TypedFunction<(), u8> = ...
```

**Comment by Outfluencer** [comment]
I'll try

**Comment by Outfluencer** [comment]
Thank you very much it is working now

**Comment by Outfluencer** [comment]
i only have the problem that i cant get "mem" or "memory" with get_memory

"Missing export mem"

**Comment by Arshia001** [comment]
The memory for the module will be initialised by `WasiEnvBuilder` and be accessible in `wasi_env`, you can get it from there.

Also, in general, you can use the `wasmer inspect` command to learn about a module's imports and exports.

**Comment by Outfluencer** [comment]
Ah i see thank you

**Comment by Arshia001** [comment]
You're welcome!

**Comment by Outfluencer** [comment]
I cant figure out how do i get access to an Memory struct

```
C:\Users\Administrator\RustroverProjects\Crust\plugins>wasmer inspect crust_example_plugin.wasm
Type: wasm
Size: 750.5 KB
Imports:
  Functions:
    "wasix_32v1"."getcwd": [I32, I32] -> [I32]
    "wasix_32v1"."futex_wait": [I32, I32, I32, I32] -> [I32]
    "wasix_32v1"."futex_wake": [I32, I32] -> [I32]
    "wasix_32v1"."futex_wake_all": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."clock_time_get": [I32, I64, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_close": [I32] -> [I32]
    "wasi_snapshot_preview1"."fd_seek": [I32, I64, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."poll_oneoff": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."proc_exit": [I32] -> []
    "wasi_snapshot_preview1"."sched_yield": [] -> [I32]
    "wasix_32v1"."callback_signal": [I32, I32] -> []
    "wasix_32v1"."thread_parallelism": [I32] -> [I32]
    "wasix_32v1"."thread_signal": [I32, I32] -> [I32]
    "wasix_32v1"."thread_exit": [I32] -> []
    "wasi"."thread-spawn": [I32] -> [I32]
  Memories:
    "env"."memory": shared (17 pages..65536 pages)
  Tables:
  Globals:
Exports:
  Functions:
    "CrustPlugin_QueryMetadata": [] -> [I32]
    "CrustPlugin_EntryPoint": [I32] -> [I32]
    "__wasm_signal": [I32] -> []
    "wasi_thread_start": [I32, I32] -> []
    "asyncify_start_unwind": [I32] -> []
    "asyncify_stop_unwind": [] -> []
    "asyncify_start_rewind": [I32] -> []
    "asyncify_stop_rewind": [] -> []
    "asyncify_get_state": [] -> [I32]
  Memories:
  Tables:
  Globals:
    "__stack_pointer": I32 (mutable)
    "__heap_base": I32 (constant)
    "__data_end": I32 (constant)

C:\Users\Administrator\RustroverProjects\Crust\plugins>
```

**Comment by Outfluencer** [comment]
is it right that there is only an import and no export?

**Comment by Outfluencer** [comment]
all methods i can see to access memory are crate public only

**Comment by Arshia001** [comment]
> is it right that there is only an import and no export?

yes, WASIX modules should import their memories. Otherwise, threads don't work.

> all methods i can see to access memory are crate public only

Ah, I was sure I'd fixed this, but the change may have been lost somewhere and not published... I'll need to update the `wasmer-wasix` crate to expose the memory-related functions. In the mean time, you'd need to add Wasmer as a git dependency or wait for the next release (shouldn't be too far off into the future).

**Comment by Outfluencer** [comment]
Okay thank you. I hope you find time to do that soon. (I created a pr of my change for now)

and i have changed it locally for myself until its in release

**Comment by Arshia001** [comment]
@Outfluencer #5331 will be merged in before the next release.

Do let us know if you run into more issues. The API of the wasix crate is not finalized, and outside feedback really helps with getting it into a shape that's useful for everyone.

**Comment by Outfluencer** [comment]
Thank you.
If i run into more issues i will report them.

But for now everything seems to work i can access the memory and parse a struct of it by a memory address without any issues
