### ISSUE TITLE
'wasmer run' crashes when the .wasm file has no functions

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#558]
Thanks for the bug report!

### Describe the bug

CraneliftModuleCodeGenerator::signatures is an Option<> type. This type is only filled in when feed_signatures is called. If the module has no functions, feed_signatures is never called. Then, in finalize we have this code:
```rust
        let (func_resolver, backend_cache) = func_resolver_builder.finalize(
            &self.signatures.as_ref().unwrap(),
            Arc::clone(&trampolines),
            handler_data.clone(),
        )?;
```
which is attempting to unwrap a None.

### Steps to reproduce

```bash
echo '(module)' > empty.wat
wat2wasm empty.wat
wasmer run empty.wasm
```

The error is 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:373:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
with a stack trace of:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:373:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: core::option::Option<T>::unwrap
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libcore/macros.rs:12
  12: <wasmer_clif_backend::code::CraneliftModuleCodeGenerator as wasmer_runtime_core::codegen::ModuleCodeGenerator<wasmer_clif_backend::code::CraneliftFunctionCodeGenerator,wasmer_clif_backend::signal::Caller,wasmer_clif_backend::code::CodegenError>>::finalize
             at lib/clif-backend/src/code.rs:308
  13: <wasmer_runtime_core::codegen::StreamingCompiler<MCG,FCG,RM,E,CGEN> as wasmer_runtime_core::backend::Compiler>::compile
             at ./wasmer/lib/runtime-core/src/codegen.rs:182
  14: wasmer_runtime_core::compile_with_config
             at lib/runtime-core/src/lib.rs:106
  15: wasmer_runtime::compile_with_config_with
             at lib/runtime/src/lib.rs:154
  16: wasmer::execute_wasm::{{closure}}
             at src/bin/wasmer.rs:406
  17: wasmer::execute_wasm
             at src/bin/wasmer.rs:424
  18: wasmer::run
             at src/bin/wasmer.rs:707
  19: wasmer::main
             at src/bin/wasmer.rs:755
  20: std::rt::lang_start::{{closure}}
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/rt.rs:64
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  24: std::panicking::try
             at src/libstd/panicking.rs:275
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: std::rt::lang_start
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/rt.rs:64
  28: main
  29: __libc_start_main
  30: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
TODO: add fuzzer-trophy tag 

Don't know when the bug was fixed but it's not in present in master branch anymore:
```
echo '(module)' > empty.wat
wat2wasm empty.wat
./target/release/wasmer run empty.wasm
execute_wasm: "ExportNotFound { name: \"main\" }"
```

**Comment by bjfish** [comment]
@pventuzelo This was fixed here: https://github.com/wasmerio/wasmer/pull/586

I've added `fuzzer-trophy` tag.

**Comment by pventuzelo** [comment]
Ok perfect, issue can be close i think ;)
