### ISSUE TITLE
`assertion failed: memory_desc.minimum.bytes().0 >= data_top`

### ISSUE THREAD

**Issue by nlewycky** [wasmerio/wasmer#588]
Thanks for the bug report!

### Describe the bug

A data section with length `i32.const -1` passes validation but triggers an assertion failure. A hard fatal error might be fine here, but an assertion implies an error of wasmer's internals.

Status of my environment:
```
$ wasmer/target/debug/wasmer -V
wasmer 0.5.7
$ rustc -V
rustc 1.38.0-nightly (cd2cd4c96 2019-07-10)
$ uname -m
x86_64
```

### Steps to reproduce

```bash
echo '(module (memory (;0;) 1) (data (;0;) (i32.const -1) "a"))' > bug.wat
wat2wasm bug.wat
wasmer/target/debug/wasmer run bug.wat
thread 'main' panicked at 'assertion failed: memory_desc.minimum.bytes().0 >= data_top', lib/runtime-core/src/backing.rs:151:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

An overlength data section is probably worth a runtime error, but it shouldn't be an assertion failure.

### Actual behavior

```
$ wasmer/target/debug/wasmer validate bug.wasm
$ RUST_BACKTRACE=1 wasmer/target/debug/wasmer run bug.wasm
thread 'main' panicked at 'assertion failed: memory_desc.minimum.bytes().0 >= data_top', lib/runtime-core/src/backing.rs:151:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/panicking.rs:411
   8: wasmer_runtime_core::backing::LocalBacking::finalize_memories
             at lib/runtime-core/src/backing.rs:151
   9: wasmer_runtime_core::backing::LocalBacking::new
             at lib/runtime-core/src/backing.rs:63
  10: wasmer_runtime_core::instance::Instance::new
             at lib/runtime-core/src/instance.rs:58
  11: wasmer_runtime_core::module::Module::instantiate
             at lib/runtime-core/src/module.rs:120
  12: wasmer::execute_wasm
             at src/bin/wasmer.rs:636
  13: wasmer::run
             at src/bin/wasmer.rs:742
  14: wasmer::main
             at src/bin/wasmer.rs:795
  15: std::rt::lang_start::{{closure}}
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/rt.rs:64
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  19: std::panicking::try
             at src/libstd/panicking.rs:275
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  22: std::rt::lang_start
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/rt.rs:64
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nlewycky** [comment]
Actually, I think my analysis was incorrect, I thought the `i32.const -1` was causing us to try and fail to allocate 4GiB. This testcase also fails:
> (module
>  (memory (;0;) 0)
>  (data (;0;) (i32.const 0) "a"))
with the same assertion failure. It looks like wasmer asserts trying to add a data segment to a zero-byte memory.

**Comment by bjfish** [comment]
I think this should be a `LinkError`, see:
https://github.com/wasmerio/wasmer/blob/33166eaf6684f7f2eba86f708c68ede3de4d017d/lib/spectests/spectests/data.wast#L167

**Comment by pventuzelo** [comment]
@nlewycky you right, the issue is with `(i32.const -1)`

When you run `bug.wasm` with `wasm-interp`:
```
$ wasm-interp bug.wasm
error: data segment is out of bounds: [4294967295, 4294967296) >= max value 65536
0000016: error: OnDataSegmentData callback failed
```

I'm currently looking at it but i think the best solution gonna be to replace the assert with an Error exception. Don't know yet which one better fit, CompileError or RuntimeError?
