### ISSUE TITLE
[wasmparser library] Assertion failed in wasmparser::operators_validator::FuncState::push_block

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#644]
This bug is related to the 3rd party library [wasmparser](https://github.com/yurydelendik/wasmparser.rs) used in wasmer

### Describe the bug

Assertion failed in `wasmparser::operators_validator::FuncState::push_block (operators_validator.rs:74)` i.e. [here](https://github.com/yurydelendik/wasmparser.rs/blob/master/src/operators_validator.rs#L74).
This issue is making wasmer to panicked.

### Status of my environment

```bash
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (0b680cfce 2019-07-09) | x86_64
```

### Steps to reproduce

Download [panic_assert_wasmparser_operators_validators.zip](https://github.com/wasmerio/wasmer/files/3481990/panic_assert_wasmparser_operators_validators.zip)
```
$ unzip panic_assert_wasmparser_operators_validators.zip
$ wasmer run panic_assert_wasmparser_operators_validators.wasm
thread 'main' panicked at 'assertion failed: stack_starts_at + index < self.stack_types.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.34.0/src/operators_validator.rs:74:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

`wasmparser` should detect and handle the error properly when calling `assert_stack_type_at`.
`wasmer` should maybe catch the panics of `wasmparser` functions and quit properly.

### Actual behavior

```
$ RUST_BACKTRACE=1 wasmer run panic_assert_wasmparser_operators_validators.wasm
thread 'main' panicked at 'assertion failed: stack_starts_at + index < self.stack_types.len()', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.34.0/src/operators_validator.rs:74:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::begin_panic
   8: wasmparser::operators_validator::FuncState::push_block
   9: wasmparser::operators_validator::OperatorValidator::process_operator
  10: <wasmparser::validator::ValidatingParser as wasmparser::parser::WasmDecoder>::read
  11: wasmer_runtime_core::codegen::validate_with_features
  12: <wasmer_runtime_core::codegen::StreamingCompiler<MCG,FCG,RM,E,CGEN> as wasmer_runtime_core::backend::Compiler>::compile
  13: wasmer_runtime_core::compile_with_config
  14: wasmer_runtime::compile_with_config_with
  15: wasmer::execute_wasm
  16: wasmer::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  21: std::panicking::try
             at src/libstd/panicking.rs:273
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

The wasm module attached is detect as invalid by multiple other wasm tools
```
$ wasm-validate panic_assert_wasmparser_operators_validators.wasm
000026f: error: expected valid block signature type
$  wasm-opt panic_assert_wasmparser_operators_validators.wasm
[parse exception: invalid wasm type: 0 (at 0:623)]
Fatal: error in parsing input
```

**Comment by pventuzelo** [comment]
wasmparser have been patched and a new version is available version 0.35.3 ([related commit](https://github.com/yurydelendik/wasmparser.rs/commit/05d3e24eaa463bea64fd0f36f14edb734760f305))

**Comment by pventuzelo** [comment]
Once wasmer updated with wasmparser 0.35.3, we get the following message:
```
./target/release/wasmer run panic_assert_wasmparser_operators_validators.wasm
execute_wasm: "Can\'t compile module: ValidationError { msg: \"blocks, loops, and ifs accept no parameters when multi-value is not enabled\" }"
```
so it's good ;)

**Comment by pventuzelo** [comment]
Not in master anymore, current execution in master branch 9068777aafb75b41dc8c34afcdcb35450515bb9b:
```
./target/release/wasmer run panic_assert_wasmparser_operators_validators.wasm 
execute_wasm: "Can\'t compile module: ValidationError { msg: \"blocks, loops, and ifs accept no parameters when multi-value is not enabled\" }"
```
