### ISSUE TITLE
[wasmer] index out-of-bound read triggered in wasmer_emscripten::utils::is_emscripten_module

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#672]
Thanks for the bug report!

### Describe the bug

An index out-of-bound issue occurs when `is_emscripten_module()` function tried to retrieve the `namespace` from the `namespace_table` (line 22).
This issue is making wasmer to panicked with the following message:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/scop/Documents/webassembly/wasmer/lib/runtime-core/src/structures/slice.rs:58:10
```

TO BE VERIFY: Similar issue can potentially occurs line 26

### Vulnerable code

https://github.com/wasmerio/wasmer/blob/5239cdb85a8ace8a2af30ab540b83da4a4fbda54/lib/emscripten/src/utils.rs#L19-L34

### Expected behavior

`is_emscripten_module` should check length of `StringTable` before accessing to it (line 22 & 26).

### Status of my environment

wasmer version: commit 5239cdb85a8ace8a2af30ab540b83da4a4fbda54
```bash
$ echo "`./target/release/wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download [panic_index_oob_is_emscripten_module.zip](https://github.com/wasmerio/wasmer/files/3496256/panic_index_oob_is_emscripten_module.zip)

```
$ unzip panic_index_oob_is_emscripten_module.zip
$ wasmer run panic_index_oob_is_emscripten_module.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/scop/Documents/webassembly/wasmer/lib/runtime-core/src/structures/slice.rs:58:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Actual behavior

```
$ RUST_BACKTRACE=1 ./target/release/wasmer run panic_index_oob_is_emscripten_module.wasm

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/scop/Documents/webassembly/wasmer/lib/runtime-core/src/structures/slice.rs:58:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: wasmer_runtime_core::module::StringTable<K>::get
  12: wasmer_emscripten::utils::is_emscripten_module
  13: wasmer::execute_wasm
  14: wasmer::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  19: std::panicking::try
             at src/libstd/panicking.rs:275
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  22: main
  23: __libc_start_main
  24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

The wasm module attached is a valid module and look like that:-x 
``` bash
$ wasm-validate panic_index_oob_is_emscripten_module.wasm                                                                               
$ wasm-objdump -x panic_index_oob_is_emscripten_module.wasm
panic_index_oob_is_emscripten_module.wasm:  file format wasm 0x1
Section Details:

Type[2]:
 - type[0] (i32, i32) -> i32
 - type[1] (i32) -> nil
Import[1]:
 - func[0] sig=1 <abort> <- env.abort

$ wasm-dis panic_index_oob_is_emscripten_module.wasm
(module
 (type $0 (func (param i32 i32) (result i32)))
 (type $1 (func (param i32)))
 (import "env" "abort" (func $fimport$0 (param i32)))
)
```

**Comment by pventuzelo** [comment]
TODO: add fuzzer-trophy tag for this issue

**Comment by bjfish** [comment]
I had difficulty recreating this on the latest master, are you able to recreate?

**Comment by bjfish** [comment]
@pventuzelo Please try cleaning the cache `wasmer cache clean` and then run it a few times to see if you can recreate the issue.

**Comment by pventuzelo** [comment]
Works well after cache cleaned ;)
