### ISSUE TITLE
[wasmer] panic! triggered in run_emscripten_instance (lib/emscripten/src/lib.rs)

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#685]
Thanks for the bug report!

### Describe the bug

panic! is called when the emscripten main function has received an incorrect number of parameters.
This issue is making wasmer to panicked.

https://github.com/wasmerio/wasmer/blob/6e8baf3c89e16766b1c0444dc863db80b98dffff/lib/emscripten/src/lib.rs#L375-L379

### Expected behavior

`wasmer` should generate an exception and quit properly i.e. replacing `panic!(...)` by `Err(...)`

### Status of my environment

wasmer version: commit 6e8baf3c89e16766b1c0444dc863db80b98dffff

```bash
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download 
[panic_run_emscripten_instance.zip](https://github.com/wasmerio/wasmer/files/3509042/panic_run_emscripten_instance.zip)

```
$ unzip panic_run_emscripten_instance.zip
$ ./target/release/wasmer run panic_run_emscripten_instance.wasm
thread 'main' panicked at 'The emscripten main function has received an incorrect number of params 3', lib/emscripten/src/lib.rs:376:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Actual behavior

```
$ RUST_BACKTRACE=1 wasmer run panic_run_emscripten_instance.wasm

thread 'main' panicked at 'The emscripten main function has received an incorrect number of params 3', lib/emscripten/src/lib.rs:369:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:337
   9: wasmer_emscripten::run_emscripten_instance
  10: wasmer::execute_wasm
  11: wasmer::main
  12: std::rt::lang_start::{{closure}}
  13: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  14: std::panicking::try::do_call
             at src/libstd/panicking.rs:294
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: std::panicking::try
             at src/libstd/panicking.rs:273
  17: std::panic::catch_unwind
             at src/libstd/panic.rs:388
  18: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  19: main
  20: __libc_start_main
  21: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
TODO: add fuzzer-trophy tag
