### ISSUE TITLE
[wasmer] Assertion failed in get_emscripten_[table_size,memory_size] (lib/emscripten/src/utils.rs)

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#686]
Thanks for the bug report!

### Describe the bugs

`assert!` is called when the module (compiled with emscripten) doesn't contains any imported table or imported memory.

Those issues are making wasmer to panicked.

https://github.com/wasmerio/wasmer/blob/6e8baf3c89e16766b1c0444dc863db80b98dffff/lib/emscripten/src/utils.rs#L36-L52

### Expected behavior

`get_emscripten_table_size` and `get_emscripten_memory_size` should return a `Result` type.

Return value should be check when those functions are called (i.e. inside `EmscriptenGlobals::new`) and throws an exception properly.

https://github.com/wasmerio/wasmer/blob/9ef986b5749939bc60176bdb5194a5a4f783f269/lib/emscripten/src/lib.rs#L461-L462

### Status of my environment

wasmer version: commit 6e8baf3c89e16766b1c0444dc863db80b98dffff

```bash
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download 
[panic_assert_get_emscripten_table_size.zip](https://github.com/wasmerio/wasmer/files/3510028/panic_assert_get_emscripten_table_size.zip)

```
$ unzip panic_assert_get_emscripten_table_size.zip
$ ./target/release/wasmer run panic_assert_get_emscripten_table_size.wasm
thread 'main' panicked at 'Emscripten requires at least one imported table', lib/emscripten/src/utils.rs:37:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Actual behavior

```
$ RUST_BACKTRACE=1 wasmer run panic_assert_get_emscripten_table_size.wasm
thread 'main' panicked at 'Emscripten requires at least one imported table', lib/emscripten/src/utils.rs:37:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
   8: wasmer_emscripten::EmscriptenGlobals::new
   9: wasmer::execute_wasm
  10: wasmer::main
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  13: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: std::panicking::try
             at src/libstd/panicking.rs:275
  16: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  17: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
TODO: add fuzzer-trophy tag

**Comment by orangeSi** [comment]
I still get this error:
```
$ wasmer run reported_issues/panic_assert_get_emscripten_table_size.wasm 
error: failed to run `reported_issues/panic_assert_get_emscripten_table_size.wasm`
╰─> 1: Emscripten requires at least one imported table

$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 2.0.0 | rustc 1.50.0 (cb75ad5db 2021-02-10) | x86_64
```

**Comment by EMUNES** [comment]
I still get this error, too:

```
❯ wasmer a.out.wasm
error: failed to run `a.out.wasm`
╰─▶ 1: Emscripten requires at least one imported table
```
Environment:
```
wasmer 2.2.0 

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.13
Ubuntu clang version 13.0.0-2
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/bin
```

C source code:

```
#include <stdio.h>

int main() {
  printf("hello, world!\n");
  return 0;
}
```

Compiling to wasm by running: `emcc hello_world.c`.

Incompatible with newer emscripten version? Thanks if there is any hint.
