### ISSUE TITLE
[wasmer] panic! 'wasm trap occured' triggered in execute_wasm (sr/bin/wasmer.rs)

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#724]
Thanks for the bug report!

### Describe the bug

`panic!` is called (line 679) when `err` match `RuntimeError::Trap`.
This issue is making wasmer to panicked.

https://github.com/wasmerio/wasmer/blob/854b2013ea6f52d5d4d9a145e6607e5fa0cf573b/src/bin/wasmer.rs#L677-L690

Also, another `panic!` is present line 689.

### Expected behavior

`wasmer` should generate an exception (or forward current ones) and then quit properly.

Also, please note that the trap generate by this wasm module is valid, the module has been designed to try an indirect call to an invalid index at runtime.

### Status of my environment

wasmer version: commit 854b2013ea6f52d5d4d9a145e6607e5fa0cf573b

```bash
echo "`./target/release/wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download 
[panic_wasm_trap_occured_call_indirect.zip](https://github.com/wasmerio/wasmer/files/3540899/panic_wasm_trap_occured_call_indirect.zip)

```
$ unzip panic_wasm_trap_occured_call_indirect.zip
$ ./target/release/wasmer run panic_wasm_trap_occured_call_indirect.wasm
sizeof(UAFME) = 4
thread 'main' panicked at 'wasm trap occured: `call_indirect` out-of-bounds', src/bin/wasmer.rs:679:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

### Actual behavior (release build)

```
$ RUST_BACKTRACE=1 ../target/release/wasmer run panic_wasm_trap_occured_call_indirect.wasm
sizeof(UAFME) = 4
thread 'main' panicked at 'wasm trap occured: `call_indirect` out-of-bounds', src/bin/wasmer.rs:679:55
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: wasmer::execute_wasm
  10: wasmer::main
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  13: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  15: std::panicking::try
             at src/libstd/panicking.rs:275
  16: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  17: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
****

**Comment by pventuzelo** [comment]
After the patch:
```
./target/release/wasmer run reported_issues/panic_wasm_trap_occured_call_indirect.wasm 
sizeof(UAFME) = 4
execute_wasm: "wasm trap occured: `call_indirect` out-of-bounds"
```

**Comment by pventuzelo** [comment]
TODO: merge https://github.com/wasmerio/wasmer/pull/747
