### ISSUE TITLE
[wasmer] panic due to improper unwrap in LocalBacking::generate_memories

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#725]
Thanks for the bug report!

### Describe the bug

`panic` error occurs in `LocalBacking::new` when calling `generate_memories` method. This issue is due to an improper check of the `Memory::new` return type lading to an unwrap failed.

https://github.com/wasmerio/wasmer/blob/854b2013ea6f52d5d4d9a145e6607e5fa0cf573b/lib/runtime-core/src/backing.rs#L119-L126

`Memory::new` return `Result<Self, CreationError>`

https://github.com/wasmerio/wasmer/blob/854b2013ea6f52d5d4d9a145e6607e5fa0cf573b/lib/runtime-core/src/memory/mod.rs#L67

This issue are making wasmer to panicked.

### Expected behavior

`Result` type of `Memory::new` should be check and `CreationError` should be handle properly.

ex: `let memory = Memory::new(desc)?;`

### Status of my environment

wasmer version: commit 854b2013ea6f52d5d4d9a145e6607e5fa0cf573b

```bash
echo "`./target/release/wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.6.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

### Steps to reproduce

Download 
[panic_unwrap_LocalBacking_generate_memories.zip](https://github.com/wasmerio/wasmer/files/3541600/panic_unwrap_LocalBacking_generate_memories.zip)

```
$ unzip panic_unwrap_LocalBacking_generate_memories.zip
$ ./target/release/wasmer run panic_unwrap_LocalBacking_generate_memories.wasm
thread 'main' panicked at 'unable to create memory: InvalidDescriptor("Max number of pages is required for shared memory")', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Actual behavior

```
$ RUST_BACKTRACE=1 ./target/release/wasmer run panic_unwrap_LocalBacking_generate_memories.wasm
thread 'main' panicked at 'unable to create memory: InvalidDescriptor("Max number of pages is required for shared memory")', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: wasmer_runtime_core::backing::LocalBacking::new
  12: wasmer_runtime_core::instance::Instance::new
  13: wasmer_runtime_core::module::Module::instantiate
  14: wasmer::execute_wasm
  15: wasmer::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  20: std::panicking::try
             at src/libstd/panicking.rs:275
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
TODO: tag with fuzzer-trophy

**Comment by pventuzelo** [comment]
Fix in pull request: https://github.com/wasmerio/wasmer/pull/772
I also removed calls to `panic!` in the rest of `backing.rs` source code.

After the fix:
```
./target/release/wasmer run panic_unwrap_LocalBacking_generate_memories.wasm 
execute_wasm: "Can\'t instantiate module: LinkError([Generic { message: \"unable to create memory: InvalidDescriptor(\\\"Max number of pages is required for shared memory\\\")\" }])"
```

**Comment by pventuzelo** [comment]
Merged here: https://github.com/wasmerio/wasmer/commit/eec1225aabd3c68ca7a1a3c1870fb1250a0fe91a
