### ISSUE TITLE
[wasmer binary] panic! index oob when emscripten entrypoint doesn't exist

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#848]
# Describe the bug

An index out of bound error make wasmer to panic when requesting fake function name with the ` --em-entrypoint` argument:
``` sh
./target/release/wasmer run --em-entrypoint abcd  emscripten_hello.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2704:10
```

### Steps to reproduce

version : 8a2052bb9017532629a307ccca763b313f3c2693
```bash
echo "`wasmer -V` | `rustc -V` | `uname -m`"
$ wasmer 0.7.0 | rustc 1.38.0-nightly (ad7c55e1f 2019-08-07) | x86_64
```

Download:  [emscripten_hello.zip](https://github.com/wasmerio/wasmer/files/3671168/emscripten_hello.zip)
Run:
``` sh
unzip emscripten_hello.zip
$ ./target/release/wasmer run --em-entrypoint abcd  emscripten_hello.wasm
```
### Expected behavior

wasmer should detect that this entrypoint doesn't exist in this module and through an error.

### Additional context (compiled in debug mode)

``` sh
RUST_BACKTRACE=1 ./target/release/wasmer run --em-entrypoint abcd  emscripten_hello.wasm
wasmer-runtime(:359) Running entry point: abcd

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2704:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2704
  12: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libcore/slice/mod.rs:2555
  13: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/liballoc/vec.rs:1791
  14: wasmer_emscripten::run_emscripten_instance
             at lib/emscripten/src/lib.rs:360
  15: wasmer::execute_wasm
             at src/bin/wasmer.rs:556
  16: wasmer::run
             at src/bin/wasmer.rs:757
  17: wasmer::main
             at src/bin/wasmer.rs:825
  18: std::rt::lang_start::{{closure}}
             at /rustc/ad7c55e1fc55d9af4787b285cec1c64e3480ae84/src/libstd/rt.rs:64
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  22: std::panicking::try
             at src/libstd/panicking.rs:275
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Hywan** [comment]
Problem solved.

I get:

```
Hello World
```

with no error.

I'm closing the issue.
