### ISSUE TITLE
[wasmer llvm backend] panic triggered by inkwell::into_floatvalue in lib/llvm-backend/src/code.rs

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#962]
### Describe the bug

`wasmer` panic when giving a particular module.
I suppose this bug is mainly caused by the byte 0xfc in the module.
Need more investigation.

``` sh
$ ./target/release/wasmer run --backend llvm panic_inkwell.wasm           
thread 'main' panicked at 'called into_floatvalue() on IntValue(IntValue { int_value: Value { name: "", address: 0x556edf7a0c40, is_const: true, is_null: false, is_undef: false, llvm_value: "i32 208", llvm_type: "i32" } })', /home/scop/.cargo/git/checkouts/inkwell-fad330d302bbed79/bd0d09a/src/values/enums.rs:52:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.1 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
Commit: d64d070c9f3c80b72560f7da87d4c7b971dc725e

### Steps to reproduce

Download: [panic_inkwell.zip](https://github.com/wasmerio/wasmer/files/3841911/panic_inkwell.zip)
Run:
``` sh
$ unzip panic_inkwell.zip
$ wasmer run --backend llvm panic_inkwell.wasm
thread 'main' panicked at 'called into_floatvalue() on IntValue(IntValue { int_value: Value { name: "", address: 0x563362ba3bc0, is_const: true, is_null: false, is_undef: false, llvm_value: "i32 208", llvm_type: "i32" } })', /home/vsts/.cargo/git/checkouts/inkwell-fad330d302bbed79/bd0d09a/src/values/enums.rs:52:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior
`wasmer` should detect the module as invalid and throws an Error.

### Actual behavior

Following the output of wasmer compiled with `cargo build --release --features backend-singlepass,backend-llvm,debug,trace`:

``` sh
RUST_BACKTRACE=full ./target/release/wasmer run --backend llvm panic_inkwell.wasm
thread 'main' panicked at 'called into_floatvalue() on IntValue(IntValue { int_value: Value { name: "", address: 0x564d43d3dc40, is_const: true, is_null: false, is_undef: false, llvm_value: "i32 208", llvm_type: "i32" } })', /home/scop/.cargo/git/checkouts/inkwell-fad330d302bbed79/bd0d09a/src/values/enums.rs:52:1
stack backtrace:
   0:     0x564d41747fdb - backtrace::backtrace::libunwind::trace::h5bc0bbbec4785b9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x564d41747fdb - backtrace::backtrace::trace_unsynchronized::hf4cf55203265c51b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x564d41747fdb - std::sys_common::backtrace::_print::h7f21be6b8a753a13
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x564d41747fdb - std::sys_common::backtrace::print::hbd10ca8c5a66607b
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x564d41747fdb - std::panicking::default_hook::{{closure}}::h1fbeb43ccddede95
                               at src/libstd/panicking.rs:200
   5:     0x564d41747cb6 - std::panicking::default_hook::hb56e8fead4dc563f
                               at src/libstd/panicking.rs:214
   6:     0x564d4174874d - std::panicking::rust_panic_with_hook::h34de78ee1c6d2416
                               at src/libstd/panicking.rs:477
   7:     0x564d417482d2 - std::panicking::continue_panic_fmt::hd2fe7034954bd46f
                               at src/libstd/panicking.rs:384
   8:     0x564d4174821f - std::panicking::begin_panic_fmt::h8c24cb76fe56186a
                               at src/libstd/panicking.rs:339
   9:     0x564d40833985 - inkwell::values::enums::BasicValueEnum::into_float_value::h2ac8151e135290cd
                               at /home/scop/.cargo/git/checkouts/inkwell-fad330d302bbed79/bd0d09a/src/values/enums.rs:11
  10:     0x564d407d0b1f - <wasmer_llvm_backend::code::LLVMFunctionCodeGenerator as wasmer_runtime_core::codegen::FunctionCodeGenerator<wasmer_llvm_backend::code::CodegenError>>::feed_event::h91d9b3a4e3e730cb
                               at lib/llvm-backend/src/code.rs:3943
  11:     0x564d40628e96 - wasmer_runtime_core::codegen::MiddlewareChain::run::h63237ebe8d2fc453
                               at /home/scop/Documents/webassembly/wasmer-repo/wasmer/lib/runtime-core/src/codegen.rs:294
  12:     0x564d4060f678 - wasmer_runtime_core::parse::read_module::heda326a76a2b2188
                               at /home/scop/Documents/webassembly/wasmer-repo/wasmer/lib/runtime-core/src/parse.rs:277
  13:     0x564d406272e8 - <wasmer_runtime_core::codegen::StreamingCompiler<MCG,FCG,RM,E,CGEN> as wasmer_runtime_core::backend::Compiler>::compile::hc0bbc24aa6e025aa
                               at /home/scop/Documents/webassembly/wasmer-repo/wasmer/lib/runtime-core/src/codegen.rs:211
  14:     0x564d416891a0 - wasmer_runtime_core::compile_with_config::hcdd376dfdc67e519
                               at lib/runtime-core/src/lib.rs:136
  15:     0x564d407925ec - wasmer_runtime::compile_with_config_with::h4156185fba90a126
                               at lib/runtime/src/lib.rs:166
  16:     0x564d4061ceab - wasmer::execute_wasm::{{closure}}::hfa583575fc99f722
                               at src/bin/wasmer.rs:499
  17:     0x564d4061ceab - wasmer::execute_wasm::h52c404e8f976f72b
                               at src/bin/wasmer.rs:521
  18:     0x564d4062267c - wasmer::run::h906b1ab63d6f61be
                               at src/bin/wasmer.rs:771
  19:     0x564d4062267c - wasmer::main::hc1c29fab9a506321
                               at src/bin/wasmer.rs:839
  20:     0x564d405fc1a3 - std::rt::lang_start::{{closure}}::hedbcff611d5e56a1
                               at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/rt.rs:64
  21:     0x564d41748153 - std::rt::lang_start_internal::{{closure}}::h65db9d490d96aefe
                               at src/libstd/rt.rs:49
  22:     0x564d41748153 - std::panicking::try::do_call::h0a8dfc516d02e0a3
                               at src/libstd/panicking.rs:296
  23:     0x564d4175081a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  24:     0x564d41748d1d - std::panicking::try::he97f564b47c32fe3
                               at src/libstd/panicking.rs:275
  25:     0x564d41748d1d - std::panic::catch_unwind::h69eb91de0c3f0a15
                               at src/libstd/panic.rs:394
  26:     0x564d41748d1d - std::rt::lang_start_internal::h38f324cb349d3cb8
                               at src/libstd/rt.rs:48
  27:     0x564d40623be8 - main
  28:     0x7f40637b0b97 - __libc_start_main
  29:     0x564d405f33da - _start
  30:                0x0 - <unknown>
```

### Additional context

This module is not consider as valid by `wasmer` himself:
``` sh
$ ./target/release/wasmer validate panic_inkwell.wasm
Error: Validation failed: stack item type does not match block item type (at offset 103)
$ ./target/release/wasmer run --backend singlepass panic_inkwell.wasm
Error: Can't compile module: InternalError { msg: "Codegen(\"CodegenError { message: \\\"not yet implemented: I32TruncUSatF32\\\" }\")" }
$ ./target/release/wasmer run --backend cranelift panic_inkwell.wasm
Error: Can't compile module: ValidationError { msg: "stack item type does not match block item type" }
```

Other tools like `wasm-validate`, reject the module because of an unexpected `0xfc` opcode.
``` sh
$ wasm-validate panic_inkwell.wasm
0000037: error: unexpected opcode: 0xfc 0x1
```

**Comment by nlewycky** [comment]
I've been looking into this, and I'm not 100% sure what's going on here. It looks like there's something about the initial input which is invalid, but which wasmparser doesn't catch early enough, as we use the validating parser which validates as it streams. We ask LLVM to produce IR which violates the type constraints, triggering the inkwell assertion, but if it didn't then wasmparser would eventually notice. I've tried creating small examples that reproduce the issue and each time, they don't. It seems like the probable fix will be to wasmparser to catch the invalid code sooner.

**Comment by pventuzelo** [comment]
Thanks @nlewycky, I will look to it.

**Comment by pventuzelo** [comment]
@nlewycky i've done some tests as well and here is some feedbacks:
* 0xfc 0x1 correspond to the opcode `I32TruncUSatF32`
* this opcode return an i32 and it's this value that trigger the inkwell assertion.
* this opcode is handle properly by wasm-validate with the `--enable-saturating-float-to-int` option.
``` sh
$ wasm-validate panic_inkwell.wasm --enable-saturating-float-to-int -v
BeginModule(version: 1)
  BeginTypeSection(5)
    OnTypeCount(1)
    OnType(index: 0, params: [], results: [f32])
  EndTypeSection
  BeginFunctionSection(2)
    OnFunctionCount(1)
    OnFunction(index: 0, sig_index: 0)
  EndFunctionSection
  BeginExportSection(13)
    OnExportCount(1)
    OnExport(index: 0, kind: func, item_index: 0, name: "calculate")
  EndExportSection
  BeginCodeSection(74)
    OnFunctionBodyCount(1)
    BeginFunctionBody(0, size:72)
    OnLocalDeclCount(1)
    OnLocalDecl(index: 0, count: 5, type: f32)
    OnF32ConstExpr(156.25 (0x04431c4000))
    OnLocalSetExpr(index: 0)
    OnF32ConstExpr(208.333 (0x0443505555))
    OnConvertExpr("i32.trunc_sat_f32_u" (1))
    OnF32ConstExpr(1.77951 (0x043fe3c715))
    OnLocalSetExpr(index: 2)
    OnLocalGetExpr(index: 1)
    OnUnaryExpr("f32.neg" (140))
    OnLocalGetExpr(index: 0)
    OnBinaryExpr("f32.mul" (148))
    OnLocalGetExpr(index: 0)
    OnLocalGetExpr(index: 2)
    OnBinaryExpr("f32.mul" (148))
    OnLocalGetExpr(index: 1)
    OnBinaryExpr("f32.sub" (147))
    OnBinaryExpr("f32.div" (149))
    OnLocalSetExpr(index: 3)
    OnLocalGetExpr(index: 1)
    OnUnaryExpr("f32.neg" (140))
    OnLocalGetExpr(index: 0)
    OnBinaryExpr("f32.mul" (148))
    OnLocalGetExpr(index: 0)
    OnLocalGetExpr(index: 2)
    OnBinaryExpr("f32.mul" (148))
    OnLocalGetExpr(index: 1)
    OnBinaryExpr("f32.sub" (147))
    OnBinaryExpr("f32.div" (149))
    OnLocalSetExpr(index: 4)
0000062: error: expected valid block signature type
```

* So the real error come from `block` at offset 60 (cmd: `wasm-objdump -ds panic_inkwell.wasm`):
```
 000060: 02 00                      | block type[0]
 000062: 00                         |   unreachable
 000063: 0b                         | end
```

* If you modify/remove those opcodes, the bug will not happened anymore so i suppose there are link in some way. 

Like you, i suggest to check validity of the module using `wasmparser` before LLVM IR generation. It seems to be the more secure way to operate and prevent other issues in the future.

**Comment by nlewycky** [comment]
Regarding #1016, I talked it over with @syrusakbary and agree we should turn on prevalidation for LLVM today, but we're not sure whether we want to do prevalidation in the long term. We'd like to minimize the number of passes of the wasm code.

In theory it seems possible to say that the backends will only be fed a prefix of valid wasm, even if the remainder of the wasm turns out to be invalid. We can't yet decide because we don't understand is how hard that would be. I'd like to start by understand how the invalid WASM in this example caused the current LLVM crash.

For the backends in Rust, we think it should be possible to constrain what bad things a backend can get up to, by minimizing the amount of unsafe code. With LLVM this may be harder, but we've worked on improving the soundness of inkwell and will continue to do so.

**Comment by pventuzelo** [comment]
@nlewycky, I've reanalyze the module this morning, and make some progress:

* offset 0x60 `block type[0]` is actually a multi-value block - [proposal](https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md)

* i succeed to minimize the module and make it a valid module by replacing a maximum of opcodes by 0x00.
* Since this new module is valid, even with pre_validation on llvm backend will generate a crash.

Here is the module: [panic_inkwell_min_unreach.zip](https://github.com/wasmerio/wasmer/files/3891013/panic_inkwell_min_unreach.zip)


Validation:
``` sh
$ wasm-validate --enable-saturating-float-to-int --enable-multi-value panic_inkwell_min_unreach.wasm
```

On wasmer:
``` sh
$ ./target/debug/wasmer run --backend llvm panic_inkwell_min_unreach.wasm 
thread 'main' panicked at 'called into_floatvalue() on IntValue(IntValue { int_value: Value { name: "", address: 0x5623a7708410, is_const: true, is_null: true, is_undef: false, llvm_value: "i32 0", llvm_type: "i32" } })', /home/scop/.cargo/git/checkouts/inkwell-fad330d302bbed79/bd0d09a/src/values/enums.rs:52:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by nlewycky** [comment]
There's an asymmetry in wabt. wasm-validate only accepts panic_inkwell_min_unreach.wasm with both `--enable-saturating-float-to-int` and `--enable-multi-value`. If you wasm2wat it, then wat2wasm the result, you only need `--enable-saturating-float-to-int`.

You can see the difference in the wasm-validate output. Original:
>     OnBlockExpr(sig: funcidx[0])
After wasm2wat | wat2wasm:
>     OnBlockExpr(sig: f32)

In MVP WebAssembly, the type of a block must be a result type, which means 0-or-1 value types, which is one of i32 | i64 | f32 | f64 (or v128 with the SIMD proposal). Having a block return a function type is invalid. With the multi-value return proposal, blocks always have function type, so that we can describe their input and outputs. Wasmparser implements the multi-value return proposal, and although it has an option to disable multi-value return, it seems that this code is allowing blocks that it shouldn't: https://sourcegraph.com/github.com/yurydelendik/wasmparser.rs/-/blob/src/operators_validator.rs#L576 . 

I think we can send wasmparser a bug report that they accept this file as valid with the multi-value return feature disabled, and wabt a bug report that with multi-value return enabled wasm2wat produces a .wat file which doesn't match the .wasm file.

**Comment by pventuzelo** [comment]
Do you want me to fill the bugs report for wabt and wasmparser or do you prefer to handle it?

**Comment by Hywan** [comment]
The bug is fixed today:

```sh
$ wasmer run --llvm /tmp/panic_inkwell.wasm
error: failed to run `/tmp/panic_inkwell.wasm`
│   1: module instantiation failed (engine: universal, compiler: llvm)
╰─> 2: Validation error: type mismatch: expected f32, found i32 (at offset 103)
```

Closing this issue.
