### ISSUE TITLE
[wasmparser library] assertion failed making wasmer to panic

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#967]
# Describe the bug

An assertion failure in `wasmparser v0.39.2` is making `wasmer` to panic:
``` sh
$ wasmer validate --enable-simd wasmparser_assert_failed_remove_frame_stack_types.wasm 
thread 'main' panicked at 'assertion failed: self.stack_types.len() >= last_block.stack_starts_at + remove_count', /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.39.2/src/operators_validator.rs:120:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Bug has been reported on wasmparser github repository [here](https://github.com/bytecodealliance/wasmparser/issues/139).

# Status of my environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.1 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
version: fff16c08d099a1db88754630eae98b5792aa689a

### Steps to reproduce

Download [wasmparser_assert_failed_remove_frame_stack_types.zip](https://github.com/wasmerio/wasmer/files/3847379/wasmparser_assert_failed_remove_frame_stack_types.zip)

### Actual behavior

``` sh
$ RUST_BACKTRACE=1 wasmer validate --enable-simd wasmparser_assert_failed_remove_frame_stack_types.wasm
thread 'main' panicked at 'assertion failed: self.stack_types.len() >= last_block.stack_starts_at + remove_count', /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmparser-0.39.2/src/operators_validator.rs:120:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
   8: wasmparser::operators_validator::FuncState::remove_frame_stack_types
   9: wasmparser::operators_validator::OperatorValidator::process_operator
  10: <wasmparser::validator::ValidatingParser as wasmparser::parser::WasmDecoder>::read
  11: wasmer_runtime_core::validate_and_report_errors_with_features
  12: wasmer::main
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  15: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  17: std::panicking::try
             at src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  19: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pventuzelo** [comment]
This bug has been fixed in this PR: https://github.com/bytecodealliance/wasmparser/pull/140
`wasmer` need to be update with `wasmparser` version = "0.39.3"

**Comment by pventuzelo** [comment]
last version of wasmparser is now 0.41.0

**Comment by pventuzelo** [comment]
waiting for https://github.com/wasmerio/wasmer/pull/975 to be merged

**Comment by pventuzelo** [comment]
This one doesn't crash anymore even if wasmparser have not been updated to version `0.39.3`.
Don't know why...

Result with current wasmer commit: 59d2b8b381d4d594c96dc367e2fe1c4d95e086a0:
```
./target/release/wasmer validate --enable-simd wasmparser_assert_failed_remove_frame_stack_types.wasm
Error: Validation failed: not enough operands (at offset 28)
```
