### ISSUE TITLE
[wasmer all backends] index OOB panic in LocalBacking::generate_globals

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#979]
### Describe the bug

`wasmer` panic with an `index out of bounds` errors when `import_global_index` is greeter than `imports.globals` length.

``` sh
$ ./target/release/wasmer run panic_index_oob_all_backends.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', lib/runtime-core/src/structures/slice.rs:65:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Issue seems to be there (line 453): https://github.com/wasmerio/wasmer/blob/5582a89e6b67af9d7d8cd764cec354dbf0165f14/lib/runtime-core/src/backing.rs#L450-L455

### Environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.1 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
commit: 5582a89e6b67af9d7d8cd764cec354dbf0165f14

### Steps to reproduce

Download: [panic_index_oob_all_backends.zip](https://github.com/wasmerio/wasmer/files/3859076/panic_index_oob_all_backends.zip)
Run:
``` sh
$ unzip panic_index_oob_all_backends.zip
$ ./target/release/wasmer run panic_index_oob_all_backends.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', lib/runtime-core/src/structures/slice.rs:65:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

`wasmer` should check if `import_global_index` is valid and through an error if not.

### Actual behavior

Following the output of wasmer compiled with cargo build --release --features backend-singlepass,backend-llvm,debug,trace:

``` sh
RUST_BACKTRACE=1 ./target/release/wasmer run panic_index_oob_all_backends.wasm
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', lib/runtime-core/src/structures/slice.rs:65:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  11: <wasmer_runtime_core::structures::slice::SliceMap<K,V> as core::ops::index::Index<K>>::index
             at lib/runtime-core/src/structures/slice.rs:65
  12: wasmer_runtime_core::backing::LocalBacking::generate_globals
             at lib/runtime-core/src/backing.rs:453
  13: wasmer_runtime_core::backing::LocalBacking::new
             at lib/runtime-core/src/backing.rs:80
  14: wasmer_runtime_core::instance::Instance::new
             at lib/runtime-core/src/instance.rs:69
  15: wasmer_runtime_core::module::Module::instantiate
             at lib/runtime-core/src/module.rs:141
  16: wasmer::execute_wasm
             at src/bin/wasmer.rs:676
  17: wasmer::run
             at src/bin/wasmer.rs:780
  18: wasmer::main
             at src/bin/wasmer.rs:848
  19: std::rt::lang_start::{{closure}}
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/rt.rs:64
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  23: std::panicking::try
             at src/libstd/panicking.rs:275
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

All backends are concerned.

**Comment by Hywan** [comment]
Thanks for the bug report!

**Comment by pventuzelo** [comment]
Your welcome ;) 
I confirm, issue fixed in master branch for all backend!
```
./target/release/wasmer run --backend llvm panic_index_oob_all_backends.wasm 
Error: Can't instantiate module: LinkError([Generic { message: "Trying to read the `0` global that is not properly initialized." }])
```
