### ISSUE TITLE
[wasmer cranelift backend] panic in cranelift-codegen-0.44.0 (ref type)

### ISSUE THREAD

**Issue by pventuzelo** [wasmerio/wasmer#980]
### Describe the bug

`wasmer` panic with `reference types were found but safepoints were not enabled.` error message.

``` sh
$ ./target/release/wasmer run panic_ref_type_not_enabled.wasm                                     
thread '<unnamed>' panicked at 'reference types were found but safepoints were not enabled.', /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/regalloc/context.rs:219:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Environment

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 0.10.1 | rustc 1.38.0-nightly (2d1a551e1 2019-08-08) | x86_64
```
commit: 5582a89e6b67af9d7d8cd764cec354dbf0165f14

### Steps to reproduce

Download: [panic_ref_type_not_enabled.zip](https://github.com/wasmerio/wasmer/files/3859166/panic_ref_type_not_enabled.zip)

Run:
``` sh
$ unzip panic_ref_type_not_enabled.zip
$ ./target/release/wasmer run panic_ref_type_not_enabled.wasm                                     
thread '<unnamed>' panicked at 'reference types were found but safepoints were not enabled.', /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/regalloc/context.rs:219:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### Expected behavior

`wasmer` should through an error instead.

### Actual behavior

Following the output of wasmer compiled with `cargo build --release --features backend-singlepass,backend-llvm,debug,trace`:

``` sh
RUST_BACKTRACE=1 ./target/release/wasmer run panic_ref_type_not_enabled.wasm --backend=cranelift
thread '<unnamed>' panicked at 'reference types were found but safepoints were not enabled.', XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/regalloc/context.rs:219:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panicking.rs:411
   8: cranelift_codegen::regalloc::context::Context::run
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/regalloc/context.rs:219
   9: cranelift_codegen::context::Context::regalloc
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/context.rs:328
  10: cranelift_codegen::context::Context::compile
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/context.rs:157
  11: cranelift_codegen::context::Context::compile_and_emit
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/context.rs:113
  12: wasmer_clif_backend::resolver::FuncResolverBuilder::new::{{closure}}
             at lib/clif-backend/src/resolver.rs:120
  13: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/ops/function.rs:244
  14: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::with::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/map_with.rs:317
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:615
  16: <core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/slice/mod.rs:3187
  17: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:615
  18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:615
  19: <core::iter::adapters::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:1445
  20: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:615
  21: <core::iter::adapters::TakeWhile<I,P> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/mod.rs:1445
  22: core::iter::traits::iterator::Iterator::fold
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/traits/iterator.rs:1783
  23: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/fold.rs:158
  24: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/while_some.rs:139
  25: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/map.rs:248
  26: <rayon::iter::map_with::MapWithFolder<C,U,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/map_with.rs:322
  27: rayon::iter::plumbing::Producer::fold_with
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/plumbing/mod.rs:110
  28: rayon::iter::plumbing::bridge_producer_consumer::helper
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/plumbing/mod.rs:438
  29: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/plumbing/mod.rs:418
  30: rayon_core::join::join_context::call_a::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/join/mod.rs:125
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panic.rs:315
  32: std::panicking::try::do_call
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panicking.rs:296
  33: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  34: std::panicking::try
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panicking.rs:275
  35: std::panic::catch_unwind
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panic.rs:394
  36: rayon_core::unwind::halt_unwinding
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/unwind.rs:17
  37: rayon_core::join::join_context::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/join/mod.rs:146
  38: rayon_core::registry::in_worker
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:853
  39: rayon_core::join::join_context
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/join/mod.rs:133
  40: rayon::iter::plumbing::bridge_producer_consumer::helper
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/plumbing/mod.rs:416
  41: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.2.0/src/iter/plumbing/mod.rs:427
  42: rayon_core::join::join_context::call_b::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/join/mod.rs:130
  43: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/job.rs:113
  44: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panic.rs:315
  45: std::panicking::try::do_call
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panicking.rs:296
  46: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  47: std::panicking::try
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panicking.rs:275
  48: std::panic::catch_unwind
             at /rustc/2d1a551e144335e0d60a637d12f410cf65849876/src/libstd/panic.rs:394
  49: rayon_core::unwind::halt_unwinding
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/unwind.rs:17
  50: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/job.rs:119
  51: rayon_core::job::JobRef::execute
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/job.rs:59
  52: rayon_core::registry::WorkerThread::execute
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:735
  53: rayon_core::registry::WorkerThread::wait_until_cold
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:719
  54: rayon_core::registry::WorkerThread::wait_until
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:693
  55: rayon_core::registry::main_loop
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:813
  56: rayon_core::registry::ThreadBuilder::run
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:58
  57: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.6.0/src/registry.rs:103
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional context

Only cranelift backend is concerned.
Since `wasmer` default backend is cranelift, running `wasmer run` even without `--backend=cranelift` will  trigger the bug.

**Comment by syrusakbary** [comment]
This should be solved in the refactor.
